/**
 * 女装选品小站 - 配置文件
 * ========================================
 * 使用说明：
 * 1. ACCESS_CODE: 全站访问口令，进站第一道门槛（所有机构统一）
 * 2. ACCOUNTS: 各机构账号密码，格式为 { username, password, agencyName }
 *    - username: 6 位纯数字账号（唯一）
 *    - password: 8 位随机密码（大小写字母+数字）
 * 3. AGENCIES: 机构名称列表（用于设置页搜索选择）
 * 4. SITE_CONFIG: 站点全局配置
 * ----------------------------------------
 * 新增机构：在 ACCOUNTS 末尾追加一条 { username, password, agencyName } 即可，
 * username 保持 6 位纯数字且全局唯一；同时把机构名追加到 AGENCIES。
 * ========================================
 */

// ===== 全站访问口令(进站第一道门槛，所有机构统一) =====
const ACCESS_CODE = "jiaer女装大卖";

// ===== 机构账号列表 =====
const ACCOUNTS = [
  { username: "361665", password: "jTVImeq7", agencyName: "Yi Yao" },
  { username: "905348", password: "Py2jQzzh", agencyName: "FJ ruixing" },
  { username: "402381", password: "xfOuVcb9", agencyName: "QIDIAN" },
  { username: "643940", password: "gw51ROXa", agencyName: "JILIANG" },
  { username: "660050", password: "bcx4RiYH", agencyName: "Longwen" },
  { username: "459115", password: "zBB5iOR8", agencyName: "TZ" },
  { username: "475524", password: "88tHKdLw", agencyName: "Lefundo" },
  { username: "456410", password: "veHPJA4E", agencyName: "xumao31" },
  { username: "335387", password: "F2BjlVuB", agencyName: "NVWA" },
  { username: "436779", password: "5l98YXGy", agencyName: "taoyi" },
  { username: "511839", password: "fIst2ZlM", agencyName: "TT MEDIA" },
  { username: "469218", password: "8IRw4MW1", agencyName: "WanHuateng" },
  { username: "488561", password: "3Vva73kT", agencyName: "haotian123" },
  { username: "282670", password: "XIaT35aS", agencyName: "7colors" },
  { username: "575410", password: "Ln0Q7L4b", agencyName: "HUIYUE" },
  { username: "126371", password: "uiOCTb2s", agencyName: "SEA IDEAL" },
  { username: "530677", password: "hS2ryJBF", agencyName: "AY media" },
  { username: "330363", password: "9TeX8DcM", agencyName: "Viva Media" },
  { username: "737630", password: "KZ2j2B9l", agencyName: "Bright forest" },
  { username: "580584", password: "OM98zyH0", agencyName: "DragonFlag" },
  { username: "793554", password: "0hQPY2Af", agencyName: "xinba" },
  { username: "734364", password: "FGvy1GNi", agencyName: "HAIJI" },
  { username: "625867", password: "jTI7vyY8", agencyName: "LANDUN" },
  { username: "828003", password: "JoZUW5Mo", agencyName: "HANGBEI" },
  { username: "700529", password: "GaZOS2kz", agencyName: "WAYMAX GLOBAL" },
  { username: "291985", password: "830DnYFK", agencyName: "2739 Agency" },
  { username: "154522", password: "yFDx9dxM", agencyName: "Global Press" },
  { username: "420261", password: "7yKOG2Jd", agencyName: "Adoredisc" },
  { username: "831892", password: "dzGhi1Eb", agencyName: "anyStarr US" },
  { username: "157142", password: "8DjO0ZpF", agencyName: "qianyuan" },
  { username: "198268", password: "lP1o90j8", agencyName: "JINGFAN" },
  { username: "773098", password: "oPdp8gVx", agencyName: "The Alps Us" },
  { username: "313222", password: "K2MKtnl6", agencyName: "WHALE.US" },
  { username: "104428", password: "P2pb6xde", agencyName: "TTS GLOBAL" },
  { username: "719806", password: "KkG0B9zU", agencyName: "BESTHOMEGOODS" },
  { username: "992562", password: "4evPE4XP", agencyName: "MTOP" },
  { username: "494279", password: "7MUFmNX6", agencyName: "Ice Emperor" },
  { username: "441907", password: "P1bq5tzK", agencyName: "CM" },
  { username: "200060", password: "Wh43Gmcx", agencyName: "TFOP" },
  { username: "327535", password: "fRnf3aMw", agencyName: "SUPERNOVA DIGITAL MEDIA UK LTD" },
  { username: "134953", password: "UINYtc0g", agencyName: "OBLIQ" },
  { username: "389094", password: "1yIdtTYT", agencyName: "Three Pandas" },
  { username: "381420", password: "Z5huGqOr", agencyName: "Anran E-commerce Studio" },
  { username: "996024", password: "ZK06muZC", agencyName: "Black flame cultural  media" },
  { username: "625274", password: "XM3Oz1Zf", agencyName: "Tide" },
  { username: "604048", password: "d3lC9qm2", agencyName: "BALEMBA" },
  { username: "736174", password: "kh0hMNiG", agencyName: "yixing" },
  { username: "393726", password: "o5MVM7Dp", agencyName: "LION" },
  { username: "793916", password: "WDHr73px", agencyName: "DOUBIAO" },
  { username: "546521", password: "k7U7Ueok", agencyName: "NEXTGEN INFLUENCER" },
  { username: "632081", password: "PdMxsh7w", agencyName: "TrendLab Media" },
  { username: "723452", password: "ys79YhUW", agencyName: "VIPStreamers Global" },
  { username: "554906", password: "1rpdU62m", agencyName: "Xanadu Global" },
  { username: "713272", password: "7qwLHtgc", agencyName: "zoco" },
  { username: "862964", password: "42Vgpd1t", agencyName: "HonestCreators" },
  { username: "424427", password: "oYIyMR8y", agencyName: "MITURE" },
  { username: "538203", password: "GVCl3Cxp", agencyName: "The Alps Media" },
  { username: "921911", password: "rxBj0g5d", agencyName: "Leixin mx" },
  { username: "771544", password: "EuRC5Nbj", agencyName: "Shenzhen Pennitech Co. Ltd" },
  { username: "635390", password: "u9nXIALu", agencyName: "MmDCT" },
  { username: "960112", password: "EzT0aVND", agencyName: "BJN" },
  { username: "933219", password: "GNKjqkk7", agencyName: "STARLIVEMEDIA" },
  { username: "487075", password: "goSCt0w2", agencyName: "FOYOO" },
  { username: "400106", password: "ntQtOlQ7", agencyName: "WEAVEX" },
  { username: "457891", password: "fE49WZgm", agencyName: "Infinity Media Global" },
  { username: "316128", password: "tkx4K8Zd", agencyName: "Qingdao CSUP ENSI Education Co., Ltd." },
  { username: "284918", password: "Xkiq6f3V", agencyName: "BEIJING DING'S YISION MEDIA CO.LTD" },
  { username: "802026", password: "3h2OBq6V", agencyName: "GREEN MOVEMENT FUTURE" },
  { username: "738794", password: "Kl8sRcbr", agencyName: "AICENTERPRISE" },
  { username: "409434", password: "h2JGA9va", agencyName: "fyy" },
  { username: "838055", password: "c0ZchpTX", agencyName: "BESTSELLER" },
  { username: "241749", password: "16PcwGcD", agencyName: "lanchuang" },
  { username: "177274", password: "aCTOMiZ2", agencyName: "Creatorflow" },
  { username: "852843", password: "9RdCBl7Y", agencyName: "Horizon Media" },
  { username: "663119", password: "gm6Ht7nM", agencyName: "KIM" },
  { username: "152210", password: "l7t8pryT", agencyName: "xinruizhi" },
  { username: "143903", password: "t9yOVJNW", agencyName: "Starry-F" },
  { username: "658241", password: "1AF2hiWA", agencyName: "SANYOU" },
  { username: "757399", password: "mFlWuy6I", agencyName: "Lantronix" },
  { username: "627347", password: "7u6a9imF", agencyName: "GANYU" },
  { username: "534301", password: "6mC9cLek", agencyName: "EnergeticeGolobal" },
  { username: "350623", password: "8eki4AzN", agencyName: "TESSERACT" },
  { username: "859727", password: "yRJf2Pj5", agencyName: "TPGold" },
  { username: "202051", password: "Li7cor9F", agencyName: "Qianning" },
  { username: "667198", password: "m1anp0Y0", agencyName: "AstraZ-MX" },
  { username: "880319", password: "EKS50lDm", agencyName: "SALC" },
  { username: "175612", password: "mV1hd6Vu", agencyName: "Flair MGMT" },
  { username: "946725", password: "XeOJ2lpC", agencyName: "WOTOHUB" },
  { username: "626910", password: "Q7s54Mvz", agencyName: "HARMONIOUSCOOPERATION MEDIA" },
  { username: "604729", password: "Tlgzb8JW", agencyName: "zcong" },
  { username: "427308", password: "uWa2luWh", agencyName: "PAIER" },
  { username: "400328", password: "63NPcTY5", agencyName: "BLUETRON" },
  { username: "869356", password: "RT1AFHDc", agencyName: "YoungCare" },
  { username: "101202", password: "abGwmQu8", agencyName: "AMX MEDIA" },
  { username: "773019", password: "9CUaYd7k", agencyName: "NOVATOK LTD" },
  { username: "106987", password: "2eZFKmQo", agencyName: "VibraVerse" },
  { username: "352233", password: "argDY7G9", agencyName: "TOP US" },
  { username: "205885", password: "tBNf3Xa3", agencyName: "HHT" },
  { username: "119611", password: "AtpRDSH4", agencyName: "Leixin us" },
  { username: "768274", password: "NBEm1o6k", agencyName: "NJ" },
  { username: "683997", password: "GrIS39qo", agencyName: "ZATEC" },
  { username: "251448", password: "Gidka5XG", agencyName: "FREE" },
  { username: "791219", password: "t7FMbPa4", agencyName: "KnowDo" },
  { username: "235873", password: "z3l9XsSZ", agencyName: "Black Flame" },
  { username: "925956", password: "HYX1T3i8", agencyName: "YunTo" },
  { username: "602776", password: "6HofvPf2", agencyName: "Social Army" },
  { username: "749441", password: "2EUH85Wz", agencyName: "StarryHive" },
  { username: "286847", password: "qGTqMN40", agencyName: "WKZS Media" },
  { username: "195750", password: "ZDL34Kdk", agencyName: "DL2" },
  { username: "683453", password: "q3ChY7Tc", agencyName: "UN CO" },
  { username: "305275", password: "ZKtN1ce9", agencyName: "RoseRoot" },
  { username: "388544", password: "k0CSVIgD", agencyName: "xiang tan wei lan" },
  { username: "725023", password: "qj4jMnSC", agencyName: "NWS US" },
  { username: "765378", password: "LNH1dpEK", agencyName: "GaoHua" },
  { username: "865389", password: "cVwk36vh", agencyName: "Wahool Shop" },
  { username: "130307", password: "xK9Oy82t", agencyName: "Trutonic Media" },
  { username: "829493", password: "LlPPnq78", agencyName: "Katrina DiMiele LLC" },
  { username: "353402", password: "0cXOWeHn", agencyName: "HENGFU" },
  { username: "732431", password: "ros6MuWF", agencyName: "The Inner Circle" },
  { username: "897274", password: "5ngu47Sp", agencyName: "The Alps UK" },
  { username: "616362", password: "8mjB7Spm", agencyName: "TABOOST" },
  { username: "440824", password: "v8BrBAGY", agencyName: "GreenRipple" },
  { username: "842919", password: "U8N9lyNf", agencyName: "FuRise" },
  { username: "191277", password: "h2SbaFEh", agencyName: "jinghang" },
  { username: "217909", password: "FbW6m8TT", agencyName: "Venus" },
  { username: "809166", password: "Vmo15oU9", agencyName: "I.F. CONCEPT LTD" },
  { username: "566010", password: "Wjhj5Y8q", agencyName: "ViralWave" },
  { username: "881720", password: "FkQfT1Gt", agencyName: "STONDA" },
  { username: "868764", password: "Av26sA1t", agencyName: "XTFOPTOK" },
  { username: "574589", password: "3yLrxZmz", agencyName: "Puff Media Group Inc" },
  { username: "378376", password: "xbm5tNGh", agencyName: "Sellery" },
  { username: "359109", password: "OwF7lrBa", agencyName: "ZhongTong" },
  { username: "945831", password: "FCDHNz5a", agencyName: "Tendencia Vestir MX" },
  { username: "233824", password: "L7X5wo0Z", agencyName: "FOR CHRIST" },
  { username: "793111", password: "NOPFlS9e", agencyName: "DALE'S PIANO" },
  { username: "982859", password: "pCz069H6", agencyName: "CLEMGO" },
  { username: "554086", password: "3FwMmcc1", agencyName: "youmihuanjing" },
  { username: "771827", password: "a5oTNIgo", agencyName: "ShanHai.QIJI" },
  { username: "759197", password: "54iDbbPK", agencyName: "XIYU" },
  { username: "619064", password: "0jAzhejR", agencyName: "shiying" },
  { username: "594455", password: "cvLdR2e3", agencyName: "Creatok" },
  { username: "436304", password: "qkJ6S1du", agencyName: "Mesoo" },
  { username: "573407", password: "C1FQUnrl", agencyName: "The Alps MX" },
  { username: "633917", password: "72aKzDCe", agencyName: "VIPStreamers GS" },
  { username: "914450", password: "QcS6anHT", agencyName: "Fashion Tap Collective" },
  { username: "359851", password: "5tuULQhN", agencyName: "YH.UK" },
  { username: "771046", password: "FkhthXs0", agencyName: "pieasant" },
  { username: "613874", password: "bG2qdD0n", agencyName: "SPARK" },
  { username: "825708", password: "6cydaL3Z", agencyName: "CRFTOPUK" },
  { username: "508377", password: "e2cXydD3", agencyName: "CreatoRev Corporation" },
  { username: "110301", password: "BGihey64", agencyName: "JOMO" },
  { username: "510653", password: "tHDS7fUI", agencyName: "MCN Iberia, SL" },
  { username: "294178", password: "BdoTk9km", agencyName: "Wesconnex.UK" },
  { username: "866079", password: "xtlO0Ys6", agencyName: "XTD" },
  { username: "688058", password: "aE07O6fk", agencyName: "Liveology US" },
  { username: "555952", password: "p6T4h3GB", agencyName: "YQ" },
  { username: "488732", password: "EK25RajB", agencyName: "zhizileye" },
  { username: "577821", password: "9RSmy6fU", agencyName: "Starpavilion" },
  { username: "725768", password: "EvJ0oTne", agencyName: "TFINE" },
  { username: "482271", password: "t00MphuF", agencyName: "MUNI" },
  { username: "825716", password: "QQJYlj7i", agencyName: "ZANXU" },
  { username: "896143", password: "f5bRr4WV", agencyName: "MX" },
  { username: "481755", password: "nLc98hGV", agencyName: "Shinetree" },
  { username: "611517", password: "NbO6D3zm", agencyName: "The Palette Network" },
  { username: "300013", password: "P10wJRCm", agencyName: "Super Fancy Squad US" },
  { username: "994942", password: "0UXypaGk", agencyName: "The Andes" },
  { username: "627884", password: "s21On6cS", agencyName: "AstraZ" },
  { username: "933633", password: "bhizNV4y", agencyName: "SELLERY CAP" },
  { username: "192132", password: "6MZFi2zD", agencyName: "MediaLabs" },
  { username: "215946", password: "8WIV2wuO", agencyName: "YIYO Intl" },
  { username: "897129", password: "sGJ1aidE", agencyName: "DecisionAI, Inc." },
  { username: "384133", password: "5hcdT4mm", agencyName: "HUAXIA" },
  { username: "289813", password: "SRnvBd4B", agencyName: "SLEIPRE" },
  { username: "514873", password: "9ExfEi5c", agencyName: "etop" },
  { username: "226163", password: "N6OvQcKF", agencyName: "OU" },
  { username: "926565", password: "aKGS3F4Q", agencyName: "Lumosland" },
  { username: "378030", password: "pp8YpYdp", agencyName: "jikeying" },
  { username: "215852", password: "xjJ9X1i2", agencyName: "Far Ahead" },
  { username: "551279", password: "pwK9JPcD", agencyName: "HDH MEDIA" },
  { username: "878785", password: "wRsvOu4g", agencyName: "PGG" },
  { username: "408778", password: "bKxb3ovy", agencyName: "PRYME" },
  { username: "181314", password: "4KrF5OsI", agencyName: "SIFANG" },
  { username: "923043", password: "JLKLP3jd", agencyName: "Taplike" },
  { username: "924308", password: "N03GmmdD", agencyName: "letgoMX" },
  { username: "794212", password: "5X6GWYIp", agencyName: "I.F. CONCEPT DE" },
  { username: "117859", password: "S899mFyg", agencyName: "The Vanguard" },
  { username: "741546", password: "nsvYEU1t", agencyName: "Junjie Cross-Border" },
  { username: "243103", password: "6GAYPVTt", agencyName: "MINTRON" },
  { username: "875875", password: "H3bgIe6b", agencyName: "Youla" },
  { username: "860021", password: "qlS8R3MK", agencyName: "THE BRAINZ" },
  { username: "273725", password: "QXq3nilo", agencyName: "XPSTART" },
  { username: "613242", password: "IqPkYsB0", agencyName: "TFOPEU" },
  { username: "246407", password: "v64V2Jms", agencyName: "Sparkling" },
  { username: "870824", password: "hMPcr7eV", agencyName: "DIGNITY DENVER" },
  { username: "985330", password: "3lJXGNiu", agencyName: "TTX media" },
  { username: "474061", password: "AsD8xju6", agencyName: "The Brainz IT" },
  { username: "340901", password: "U52dsnSS", agencyName: "Hojumbo Media" },
  { username: "658119", password: "V4zPnt4Z", agencyName: "SoCo" },
  { username: "839985", password: "oOB2bG6t", agencyName: "SWAN MEDIA" },
  { username: "991210", password: "p02W7tQM", agencyName: "The Alps EU" },
  { username: "230865", password: "hGA7KEDF", agencyName: "CreatorEmpire" },
  { username: "206359", password: "Ax1i2w5L", agencyName: "Global Trade US" },
  { username: "924433", password: "KYyA6qXU", agencyName: "sunrise cross" },
  { username: "728971", password: "zwwPLE6t", agencyName: "KLM" },
  { username: "660051", password: "Ufr4ZeeN", agencyName: "Telepathy MCN" },
  { username: "439846", password: "O5zZV4F7", agencyName: "WAN LIN" },
  { username: "172491", password: "YbDsbB7J", agencyName: "HAIYING" },
  { username: "372890", password: "Za6De6Po", agencyName: "Jiuyiyuan" },
  { username: "285703", password: "2olIxhq0", agencyName: "DA DREAM" },
  { username: "287280", password: "JpUljsd9", agencyName: "WUHAN STAR" },
  { username: "310645", password: "fZHSGex7", agencyName: "KENNEY" },
  { username: "562160", password: "E2bTCMvJ", agencyName: "Influu" },
  { username: "355309", password: "iFy1Aor8", agencyName: "Aode" },
  { username: "272897", password: "4HQtt48Y", agencyName: "FLZ Union" },
  { username: "473675", password: "JGxLSpD4", agencyName: "FireWeed" },
  { username: "941990", password: "vFFo05Ui", agencyName: "Hoshihide" },
  { username: "813524", password: "t4XqDt1X", agencyName: "Black Flame MX" },
  { username: "143629", password: "kZ3iLpHP", agencyName: "TIMEGO" },
  { username: "461152", password: "SBG0Vn6v", agencyName: "Kawaii Agency" },
  { username: "873871", password: "xubYWNX3", agencyName: "Set sail for distant trade" },
  { username: "978915", password: "FQhOEm6i", agencyName: "PIGGYPAY-JP" },
  { username: "801023", password: "OD0iD44k", agencyName: "Lingxu Trading" },
  { username: "776139", password: "g9DgkO1b", agencyName: "t-spot" },
  { username: "895928", password: "OwC8BO3Q", agencyName: "Gemdrop" },
  { username: "332267", password: "mzsQBl1J", agencyName: "ruigoukuajing" },
  { username: "477712", password: "WvTb93mY", agencyName: "Huixing cross-border" },
  { username: "217791", password: "oX7SlhNf", agencyName: "Thundrr" },
  { username: "504342", password: "42i4MyCI", agencyName: "StarRay Media" },
  { username: "952725", password: "l2LQHgbg", agencyName: "fireweed EU" },
  { username: "440259", password: "1NPiaJ1S", agencyName: "OneTrust" },
  { username: "567711", password: "0w7KuK58", agencyName: "KFD" },
  { username: "904418", password: "dqRuU1KE", agencyName: "KYRAN ZINEX" },
  { username: "858460", password: "2T5fGnDe", agencyName: "Faith Howard" },
  { username: "318946", password: "P99FCtHu", agencyName: "Ju Zi MIDEA 3" },
  { username: "953369", password: "oT77VbWE", agencyName: "10th Mountain Lacrosse, Inc" },
  { username: "892975", password: "9GBXg6ep", agencyName: "taihua" },
  { username: "803520", password: "kGT8RnrL", agencyName: "JBT" },
  { username: "839429", password: "pt45uO7E", agencyName: "Meg Taylo" },
  { username: "112631", password: "28qcoJg0", agencyName: "Star Orange" },
  { username: "354843", password: "su6vNUif", agencyName: "Liveology UK" },
  { username: "991265", password: "F4namDxe", agencyName: "mulstars" },
  { username: "800245", password: "8SPDk0JI", agencyName: "MiaoYu" },
  { username: "406036", password: "A0NjWk6M", agencyName: "Yalian" },
  { username: "316586", password: "60XnpGl4", agencyName: "yi jing chuan mei one" },
  { username: "369490", password: "BD0m2wCq", agencyName: "Gole-guli" },
  { username: "282536", password: "2XlJBXJC", agencyName: "Fission" },
  { username: "441692", password: "TC8AG0Zv", agencyName: "UMU" },
  { username: "771650", password: "ZbJrn79D", agencyName: "Lefundo Mexico" },
  { username: "416811", password: "MJzn4wmL", agencyName: "Keshundi" },
  { username: "334412", password: "bYWsT8Wu", agencyName: "Addienix Digital Media" },
  { username: "135994", password: "xbkY8mF7", agencyName: "StarLink Ltd" },
  { username: "412871", password: "AHygyYj5", agencyName: "See Hope" },
  { username: "570749", password: "may3d4EI", agencyName: "AppicPlay" },
  { username: "656909", password: "hX4BWGq1", agencyName: "XIBI" },
  { username: "326178", password: "p9U0c7SI", agencyName: "SANEC" },
  { username: "450817", password: "XQ7lpdnL", agencyName: "lavenderwind" },
  { username: "319064", password: "iD4wsqxD", agencyName: "MAAUS" },
  { username: "845224", password: "LoRhF538", agencyName: "BAOHE" },
  { username: "761277", password: "PIXuAWu5", agencyName: "GULFLIN" },
  { username: "913693", password: "gAtch7XO", agencyName: "GT MCN" },
  { username: "174032", password: "OUwPUe0e", agencyName: "YH.US" },
  { username: "724441", password: "5ZMMq2PG", agencyName: "CANTON" },
  { username: "574471", password: "sVyy51en", agencyName: "DB" },
  { username: "733440", password: "Oo3rPKz0", agencyName: "MomentiQ" },
  { username: "992479", password: "AVW056jb", agencyName: "Gmart" },
  { username: "940070", password: "16sLjTIK", agencyName: "DawnRay" },
  { username: "391265", password: "ASoy2yPR", agencyName: "WiseSurge" },
  { username: "428036", password: "EJHV1Tqn", agencyName: "seisa" },
  { username: "110410", password: "iHZ6bV7q", agencyName: "Bocen Media" },
  { username: "859588", password: "4MeWhnqX", agencyName: "LI TRADE LTD" },
  { username: "232268", password: "bsS6RG7n", agencyName: "AFFILINATION" },
  { username: "161702", password: "kDJMU94V", agencyName: "HTH" },
  { username: "250039", password: "8YmSwT67", agencyName: "Liyun" },
  { username: "780708", password: "5H93BrQ5", agencyName: "CreationDose Srl SB" },
  { username: "397345", password: "QQD2mZJa", agencyName: "Lei Xin" },
  { username: "179590", password: "vnWhq3Sp", agencyName: "Star Map" },
  { username: "179707", password: "0e68iFYp", agencyName: "ZING LAB" },
  { username: "537034", password: "eGAXg6hy", agencyName: "UTrend" },
  { username: "353366", password: "FmPN9psa", agencyName: "KESOIL" },
  { username: "773980", password: "MPylL7Ry", agencyName: "ATLAS" },
  { username: "738937", password: "CQ6nuY9Z", agencyName: "xinyue" },
  { username: "826256", password: "uDSEXa7y", agencyName: "Miture De" },
  { username: "227298", password: "Ef7oZREY", agencyName: "Rs media" },
  { username: "658772", password: "qVLqTd5D", agencyName: "PLUX" },
  { username: "496635", password: "B2cJHyFZ", agencyName: "Forstars" },
  { username: "603897", password: "uGbYb5Lw", agencyName: "SPACE DANCE" },
  { username: "627125", password: "IlzLSv2v", agencyName: "HongShuo-" },
  { username: "683327", password: "p8bUERpt", agencyName: "butter" },
  { username: "508182", password: "Fm5kjSGa", agencyName: "Guangzhou Xingliang Network Technology Co" },
  { username: "445705", password: "MjKy9Na8", agencyName: "Dongguan Maixiang Hardware Products Co., Ltd." },
  { username: "420929", password: "b7vpO2hm", agencyName: "Plain sailing" },
  { username: "752982", password: "FkJFr3u4", agencyName: "Lefundo Studio" },
  { username: "424858", password: "PjTZl6pA", agencyName: "handlababy_xx" },
  { username: "823821", password: "LXpH9J4d", agencyName: "Star Fusion" },
  { username: "949773", password: "2mzU6KOE", agencyName: "Elephant Media" },
  { username: "696144", password: "Soh8Wc4j", agencyName: "YINGGUO" },
  { username: "721839", password: "SoWe71dW", agencyName: "TuoLiDi" },
  { username: "833702", password: "NWpGyxU6", agencyName: "SHENZHEN YUEWEN NETWORK TECHNOLOGY CO., LTD" },
  { username: "604391", password: "wjX64gSH", agencyName: "PrettiGoodz" },
  { username: "782127", password: "K8GgVlq0", agencyName: "JIANGDONG MEDIA" },
  { username: "460183", password: "p9X5545Z", agencyName: "partheamedia" },
  { username: "631004", password: "IkX1vwKR", agencyName: "XINGXING.Media" },
  { username: "758940", password: "73OgnZLq", agencyName: "qian hong" },
  { username: "988065", password: "A2bWI44q", agencyName: "Uango" },
  { username: "231990", password: "CcwRl40j", agencyName: "UNVSTAR" },
  { username: "931410", password: "PtvR6sJa", agencyName: "KFisher" },
  { username: "622057", password: "Rp44cEha", agencyName: "WEILAN" },
  { username: "349840", password: "iO1X5HEU", agencyName: "DXX" },
  { username: "186960", password: "m8jhM00p", agencyName: "TNTU" },
  { username: "537660", password: "2GLeQqsk", agencyName: "EllaGrace" },
  { username: "164118", password: "E6gxlD9B", agencyName: "A Dream" },
  { username: "766685", password: "P6wvkmn9", agencyName: "LINGS" },
  { username: "247742", password: "NvjtmK4v", agencyName: "HAIPAI" },
  { username: "953319", password: "I8tf5Pqg", agencyName: "MEIX" },
  { username: "683640", password: "E8aWhy89", agencyName: "STAR GROOP LTD" },
  { username: "527199", password: "8EUoVloV", agencyName: "LumaLink" },
  { username: "578660", password: "Xy9UyFJm", agencyName: "SWIER" },
  { username: "425079", password: "AskaNQD4", agencyName: "Media Production" },
  { username: "284521", password: "FY67fiQO", agencyName: "AquaPulse" },
  { username: "597891", password: "6lY8ek5c", agencyName: "FBOP" },
  { username: "678960", password: "wvtrE7xf", agencyName: "LiveTop Media" },
  { username: "798394", password: "F1kaXa4O", agencyName: "Quanzhouwanwan" },
  { username: "286894", password: "pP1m0Wx8", agencyName: "BounceVerse" },
  { username: "759953", password: "jgkajqG2", agencyName: "TAILE" },
  { username: "600510", password: "IxDab6fG", agencyName: "ForStar" },
  { username: "550253", password: "XqtjFKU9", agencyName: "KAIKAI NETWORK" },
  { username: "730920", password: "4FtppDD5", agencyName: "TecDo Hong Kong Limited" },
  { username: "941074", password: "4CjM2LuG", agencyName: "NEXTPOP" },
  { username: "262471", password: "n0TQ17t5", agencyName: "WMedia" },
  { username: "459341", password: "Mg6ZTxOb", agencyName: "hongyun.Mea" },
  { username: "276209", password: "E1oa6S7E", agencyName: "SPARK UK" },
  { username: "492220", password: "6yGSpQEQ", agencyName: "Cora" },
  { username: "677511", password: "k6prBLcH", agencyName: "CHQ Agency" },
  { username: "815886", password: "99JXsnIL", agencyName: "WUYUAN" },
  { username: "980339", password: "7vN9ddKP", agencyName: "X S D" },
  { username: "111914", password: "GtaaD3BL", agencyName: "ENGOOD" },
  { username: "169371", password: "LSJ9le6c", agencyName: "AuroraX Media" },
  { username: "263359", password: "4BCqNNll", agencyName: "CHECK AZUL MEDIA" },
  { username: "124060", password: "Pa6EhDD8", agencyName: "Aura Digital Solutions" },
  { username: "541892", password: "86HUbLH0", agencyName: "THROUGH ONE" },
  { username: "217744", password: "y66lZ9Gn", agencyName: "fyyk" },
  { username: "641000", password: "3Tkb3LXi", agencyName: "Hua Yuan" },
  { username: "975412", password: "6Jq7DT8g", agencyName: "JYKJ8" },
  { username: "410733", password: "7laU5fun", agencyName: "Giame Creator Collective" },
  { username: "559101", password: "JC0BSbI9", agencyName: "Charm" },
  { username: "900903", password: "TiXsw5Wv", agencyName: "YYS" },
  { username: "326729", password: "w6ycXZvt", agencyName: "MAXisMore" },
  { username: "766656", password: "FJJ6nGBb", agencyName: "Jingli" },
  { username: "842326", password: "cRE5L8oi", agencyName: "JuGeEnergy" },
  { username: "121702", password: "Hu15HB5u", agencyName: "Apex Media" },
  { username: "832583", password: "emTw3ACj", agencyName: "Supernova Ddigital" },
  { username: "245169", password: "Z56rOlxS", agencyName: "T-ART" },
  { username: "494491", password: "zw3V0deJ", agencyName: "CMRL" },
  { username: "300143", password: "wc3qfOl1", agencyName: "Creative Fun UK" },
  { username: "851777", password: "iZfs66qW", agencyName: "fat head fish" },
  { username: "938287", password: "N3yABR1P", agencyName: "Influence Assembly" },
  { username: "126623", password: "5BH9P9hy", agencyName: "GANCE" },
  { username: "631132", password: "yT2pdsZZ", agencyName: "XMYH" },
  { username: "584696", password: "RyJ07rRz", agencyName: "Orri Hub" },
  { username: "215492", password: "t1tM2FBz", agencyName: "DingLI" },
  { username: "102073", password: "yOk1zBnF", agencyName: "WISHFUL TAP" },
  { username: "117711", password: "A2IcUjaL", agencyName: "aifenxiang" },
  { username: "907688", password: "qIUD6m1X", agencyName: "Lais MediaAB" },
  { username: "213487", password: "XnFts2Ya", agencyName: "All-star" },
  { username: "535638", password: "mHvfNGs2", agencyName: "Starry" },
  { username: "905615", password: "vUOWNK4d", agencyName: "SellSpree" },
  { username: "362448", password: "XVk4s3hN", agencyName: "MRONOS" },
  { username: "712266", password: "vI3c0D2s", agencyName: "Avorio Cultura" },
  { username: "825967", password: "WzGh4Iiu", agencyName: "AFFINITY . MEDIA" },
  { username: "478179", password: "1YwUjf8J", agencyName: "TMMB" },
  { username: "663937", password: "qseW2cZ0", agencyName: "baoli" },
  { username: "109426", password: "4mUJvG0r", agencyName: "MAIJIN" },
  { username: "476863", password: "6MvoaAl3", agencyName: "ProHive" },
  { username: "239159", password: "2TD8LtSz", agencyName: "Guangzhou Jinyang E-Commerce Co., Ltd" },
  { username: "509282", password: "KEPLI96w", agencyName: "JZ One" },
  { username: "982551", password: "0fomWdKq", agencyName: "OK ARE YOU" },
  { username: "225446", password: "RdAvBEd1", agencyName: "TaiGu Media" },
  { username: "182470", password: "YfM21Znk", agencyName: "Yako" },
  { username: "106084", password: "OYDzWxx9", agencyName: "Qi ming" },
  { username: "268660", password: "5kYGGC8X", agencyName: "YooFinds" },
  { username: "562216", password: "f5oUt48B", agencyName: "JK" },
  { username: "253258", password: "2hvV4UNC", agencyName: "SHENSI" },
  { username: "573350", password: "QWDtY0Kh", agencyName: "ZHIYANTK" },
  { username: "748552", password: "o0LhFF6p", agencyName: "FirstLaunch  TAP" },
  { username: "250133", password: "C5yQoqp2", agencyName: "JOMO Media" },
  { username: "263872", password: "GhlZn7Po", agencyName: "CROSS YOUNG" },
  { username: "665461", password: "ZjdK8ZvL", agencyName: "XINIU" },
  { username: "834780", password: "R8C9n5Bw", agencyName: "Rockies" },
  { username: "232640", password: "P2wYB3pk", agencyName: "SPARK+" },
  { username: "615174", password: "kRhb4N9D", agencyName: "EasyMedia" },
  { username: "403051", password: "tVa7HYXk", agencyName: "TIANBOLUN" },
  { username: "848729", password: "p2mgU3TG", agencyName: "CarterPulse" },
  { username: "140562", password: "n0V4tXuS", agencyName: "GGREEN TRADE" },
  { username: "432451", password: "Cjz1fO01", agencyName: "CREATOOR" },
  { username: "270600", password: "tn69kNPG", agencyName: "TimeChasing" },
  { username: "115429", password: "H87X25Sg", agencyName: "OUTLIER." },
  { username: "241499", password: "WrtXlEF9", agencyName: "TONGQIKUAJING" },
  { username: "361840", password: "k5d1kEOx", agencyName: "Rowan Tech" },
  { username: "707695", password: "vI0GvFcC", agencyName: "NOW PLAN" },
  { username: "716279", password: "e4DUFlgL", agencyName: "Take-Copter" },
  { username: "957981", password: "hReOHM3X", agencyName: "Huaiaer" },
  { username: "808874", password: "yfd32M1k", agencyName: "Free Eagle" },
  { username: "895306", password: "llbEqyP9", agencyName: "FullMind Media" },
  { username: "268258", password: "x14r2khI", agencyName: "The Brainz MX" },
  { username: "171492", password: "N0yzyF22", agencyName: "stellarseek es" },
  { username: "272704", password: "1SLJcvY9", agencyName: "SHENZHEN HUIFU ADVERTISING DESIGN CO., LTD" },
  { username: "802556", password: "FEqr9336", agencyName: "On Impacts" },
  { username: "409756", password: "oY8hQC0i", agencyName: "The Brainz Global" },
  { username: "173707", password: "miJuYmk0", agencyName: "enjoyholiday" },
  { username: "543549", password: "b6uqROjJ", agencyName: "sanhang" },
  { username: "676739", password: "uSUvb1gZ", agencyName: "LUNAHOLM" },
  { username: "225758", password: "vfvXtIQ1", agencyName: "HOTSALE" },
  { username: "851016", password: "hq9PsxMH", agencyName: "Kevin E-commerce" },
  { username: "608961", password: "OMgte8yG", agencyName: "SFLIFUYHJII LLC" },
  { username: "325574", password: "zhAG9Utf", agencyName: "PrimePicks" },
  { username: "986688", password: "lwP88FvJ", agencyName: "YX" },
  { username: "145074", password: "C3z9Kvya", agencyName: "Foreversea UK" },
  { username: "508955", password: "CI9Tx6g9", agencyName: "BORG RISE" },
  { username: "273726", password: "CpL9KCFs", agencyName: "P2P Agency" },
  { username: "235350", password: "l0KRfsdx", agencyName: "QZteam" },
  { username: "694673", password: "5IhS3RJH", agencyName: "blue shark" },
  { username: "972162", password: "Mu6PhJ3J", agencyName: "Go ashore" },
  { username: "117381", password: "cdkeH35e", agencyName: "JINNIUHUI" },
  { username: "603230", password: "OS5SdVCb", agencyName: "youdianniudianshang" },
  { username: "526637", password: "ESUL7ts9", agencyName: "Deg Lin" },
  { username: "792947", password: "cRmJj096", agencyName: "Mainland MCN Consulting" },
  { username: "910038", password: "3lP3vSu1", agencyName: "bingrun" },
  { username: "367213", password: "Fs0I4Vph", agencyName: "Elowen" },
  { username: "203726", password: "jAQgCyi7", agencyName: "KawaStudio" },
  { username: "445008", password: "2GWn4kVr", agencyName: "chaolian media" },
  { username: "717330", password: "ri68juAL", agencyName: "Memo USA" },
  { username: "736694", password: "X2D4j5Jl", agencyName: "SLDZCN" },
  { username: "190330", password: "Jjyg93Kp", agencyName: "Wavegen Marketing UK" },
  { username: "448490", password: "i5W9IHhA", agencyName: "FISH" },
  { username: "645858", password: "7V2j92Mg", agencyName: "CHC Fashion Group US" },
  { username: "406949", password: "Fk4vXNZp", agencyName: "Wild Fire" },
  { username: "186202", password: "V2eziSqw", agencyName: "DOME SKY" },
  { username: "948768", password: "Fr20jktZ", agencyName: "Zmingsi&ZMSMedia." },
  { username: "155296", password: "gNGE037s", agencyName: "Yangda Alliance" },
  { username: "111418", password: "R5uig8kA", agencyName: "influu USA" },
  { username: "788512", password: "2qft67uL", agencyName: "Social Army MX" },
  { username: "781499", password: "dCCmsr9J", agencyName: "Everest Group" },
  { username: "576992", password: "W5GczuLJ", agencyName: "LAPA.uk" },
  { username: "255998", password: "xU8w7IWl", agencyName: "yinlangchuanmei" },
  { username: "566950", password: "00ZLqjQC", agencyName: "SYN FAMECOMMS" },
  { username: "156284", password: "MHG95k2f", agencyName: "puff media" },
  { username: "612764", password: "1zJa1L0e", agencyName: "Pegasusus" },
  { username: "671702", password: "9MV29pmR", agencyName: "YH.MEX" },
  { username: "270389", password: "5Vjx6puh", agencyName: "score US" },
  { username: "209301", password: "3sgY5tse", agencyName: "Goumee Tech" },
  { username: "522535", password: "kjLn9JaZ", agencyName: "Now Amuse" },
  { username: "254571", password: "8rJkIE0n", agencyName: "Boosteo" },
  { username: "178281", password: "7FIUlvSw", agencyName: "Creatorev Mexico" },
  { username: "983631", password: "4lKX4iY4", agencyName: "LAPA-BYS" },
  { username: "543278", password: "UfSH3onW", agencyName: "PUYAN" },
  { username: "925549", password: "YuoS24UR", agencyName: "UVW" },
  { username: "120050", password: "399pBqB0", agencyName: "DIAURA AGENCY" },
  { username: "452002", password: "3MUTPaTr", agencyName: "NextWave" },
  { username: "772118", password: "Jy5NRnVa", agencyName: "Twee" },
  { username: "741463", password: "A9SNjE6u", agencyName: "stacy" },
  { username: "537794", password: "oKGQ9uQp", agencyName: "Trove Land" },
  { username: "992817", password: "sclP5if1", agencyName: "NAMIZU" },
  { username: "397443", password: "V0z1hWmZ", agencyName: "zeka" },
  { username: "232500", password: "WOP1mTsz", agencyName: "CreatoRev UK" },
  { username: "755244", password: "IKnsZR5c", agencyName: "MIMIMIAO" },
  { username: "583329", password: "fBM0PfdV", agencyName: "Mediamz US" },
  { username: "999975", password: "PSGO3S6p", agencyName: "CHINHO US" },
  { username: "642833", password: "PcxB4QBG", agencyName: "4Creatorz" },
  { username: "139587", password: "VPb874Aq", agencyName: "Yunnan Maijia International Import and Export Co., Ltd." },
  { username: "990756", password: "fdZ40nKK", agencyName: "ViralWave_UK" },
  { username: "906040", password: "IhCe0GLT", agencyName: "WHHK" },
  { username: "428257", password: "qJG5qt7V", agencyName: "X-PRO LLC" },
  { username: "692416", password: "6fJOCi4N", agencyName: "Famous creators media" },
  { username: "869083", password: "Xcsj7D0t", agencyName: "Grail" },
  { username: "897125", password: "3Otf7htR", agencyName: "Liancheng International" },
  { username: "281938", password: "nViXUH60", agencyName: "42 TALENT AGENCY" },
  { username: "831164", password: "f1Py8DYi", agencyName: "senbo" },
  { username: "480218", password: "neS3exZt", agencyName: "jianjuansha" },
  { username: "960234", password: "Hba26oTD", agencyName: "SZMXFW" },
  { username: "601892", password: "2SyvwTct", agencyName: "TapTap" },
  { username: "398776", password: "xEjSBd5U", agencyName: "AIT" },
  { username: "168041", password: "3FfcDuDr", agencyName: "FOXLOLYUK" },
  { username: "495408", password: "zrq3U2mp", agencyName: "SYMS" },
  { username: "201421", password: "k0C7gFQj", agencyName: "Gmart-MXN" },
  { username: "546555", password: "AJuH5dUR", agencyName: "HTS Group" },
  { username: "739455", password: "Vx1hQI8F", agencyName: "Burst" },
  { username: "581927", password: "sqSW5nif", agencyName: "SAICHU" },
  { username: "278996", password: "TPA0h24G", agencyName: "NoAging.IT" },
  { username: "577130", password: "V9cF7sIx", agencyName: "VibraVers_SP" },
  { username: "737280", password: "Dl1Ek3oC", agencyName: "Qibang" },
  { username: "565678", password: "iz59INLB", agencyName: "Imprint Interactive" },
  { username: "706101", password: "if1EKRUZ", agencyName: "Laixiu" },
  { username: "582983", password: "Md3fpIRW", agencyName: "beeg1" },
  { username: "195003", password: "zY5vKqpx", agencyName: "QiYi Online Media" },
  { username: "841746", password: "xe0leoID", agencyName: "HEAVEN" },
  { username: "456862", password: "yUCFieB2", agencyName: "TokSurge" },
  { username: "306694", password: "u6on4e9T", agencyName: "Trend Spot" },
  { username: "591302", password: "eVobA1h2", agencyName: "VibraVers FR" },
  { username: "644267", password: "6cZk57E4", agencyName: "Sellery Spain" },
  { username: "689350", password: "t8pyLH7s", agencyName: "Media Publishers LLC" },
  { username: "247108", password: "dak9zZml", agencyName: "WOTOHUB LIMITED" },
  { username: "893780", password: "P4GC66zQ", agencyName: "BlueVelvet" },
  { username: "410171", password: "dJ0oWI1U", agencyName: "TT Media EU" },
  { username: "550305", password: "0kyC0bmg", agencyName: "VibraVers GM" },
  { username: "963167", password: "9YWJNU6w", agencyName: "WANXIAO" },
  { username: "930558", password: "sXW7Hf4e", agencyName: "XINGLIU" },
  { username: "256746", password: "pB7Bh22h", agencyName: "SUN Entertainmont" },
  { username: "763464", password: "c6ZarQsG", agencyName: "Xinchuang" },
  { username: "907279", password: "iPv80mp3", agencyName: "SailsLink Ltd" },
  { username: "377043", password: "3Ujjla3a", agencyName: "OrangePeel" },
  { username: "813901", password: "9vv3vPNN", agencyName: "FNPWR" },
  { username: "969268", password: "64r2qMSp", agencyName: "IR Creartor" },
  { username: "517004", password: "R3ETyGCf", agencyName: "TTY Technology" },
  { username: "656201", password: "xzNU8Gfs", agencyName: "xingze" },
  { username: "155332", password: "eZXlO4iz", agencyName: "URL genius" },
  { username: "510255", password: "B7RUg7Y4", agencyName: "sunrise cross-border" },
  { username: "642614", password: "FwfxJ45M", agencyName: "TTG" },
  { username: "134280", password: "rqUK7fU0", agencyName: "The Fast Track Girl" },
  { username: "200423", password: "40n5xjyT", agencyName: "Tabletop Media" },
  { username: "189465", password: "RRc6rpst", agencyName: "LA ATUNERIA DE LOS CURRICANES" },
  { username: "343708", password: "7PCdn5at", agencyName: "Toplus" },
  { username: "939771", password: "ur6IWwAD", agencyName: "DOULINK" },
  { username: "998670", password: "6WEbeiRH", agencyName: "Live Legion" },
  { username: "863766", password: "8Jcm5ms3", agencyName: "Northern Media" },
  { username: "367384", password: "Lq42l2pd", agencyName: "Starshine Creative" },
  { username: "163376", password: "6rd7V9qG", agencyName: "Outlandish Digital Spain" },
  { username: "292678", password: "2o4C5qaX", agencyName: "Euka" },
  { username: "680396", password: "UyWYvNa9", agencyName: "TikMarketing" },
  { username: "219744", password: "6cLEGQwZ", agencyName: "SailingMedia" },
  { username: "215107", password: "16dLL4vf", agencyName: "LUNAHOLM MCN" },
  { username: "608324", password: "WVA07TuD", agencyName: "MSHP LAB" },
  { username: "388218", password: "8POPaHmu", agencyName: "IMX" },
  { username: "585441", password: "D21QhztE", agencyName: "HSWang" },
  { username: "659362", password: "06S2QfNJ", agencyName: "XSTREAM" },
  { username: "176621", password: "E5Esv0H3", agencyName: "SMITH TRADING LLC" },
  { username: "640326", password: "lBrLq1n8", agencyName: "I.F. CONCEPT" },
  { username: "838209", password: "Tf33zjP9", agencyName: "5x Dashboard" },
  { username: "962891", password: "18PzIsD1", agencyName: "IcedOut MCN" },
  { username: "413512", password: "Oh87Q5E8", agencyName: "xinghangshijie" },
  { username: "534467", password: "QKtnOO4W", agencyName: "alkamest" },
  { username: "806897", password: "J0xblckx", agencyName: "Boost Engine" },
  { username: "854591", password: "2FmsZAtK", agencyName: "Media Company" },
  { username: "941082", password: "cEFWU9gO", agencyName: "LONDON AGENCY" },
  { username: "747281", password: "5NskXre7", agencyName: "ShineTiger" },
  { username: "810932", password: "DS1jS2V3", agencyName: "HLSW" },
  { username: "395000", password: "hvWc4zX5", agencyName: "Master TV MCN" },
  { username: "332462", password: "QKrtqnb2", agencyName: "ShopliveX" },
  { username: "341616", password: "A9k7LG7j", agencyName: "BLUE SHIJIE" },
  { username: "700416", password: "8IUVPZkP", agencyName: "D4N Creator Network" },
  { username: "884460", password: "Dc8JxTXh", agencyName: "Blue Bat Cafe" },
  { username: "955524", password: "uF2tN1Ju", agencyName: "Shang Jie" },
  { username: "773912", password: "nyD6LSMM", agencyName: "VastOcean" },
  { username: "836164", password: "Y0d7iyLF", agencyName: "YUE FENG WEN HUA" },
  { username: "847611", password: "nvKei82q", agencyName: "Pinteng" },
  { username: "156697", password: "aBqftLa1", agencyName: "zx" },
  { username: "572245", password: "2qZAdI8m", agencyName: "Ordient Network" },
  { username: "427353", password: "2XPH0NsF", agencyName: "Amireux" },
  { username: "732127", password: "m86fcOVQ", agencyName: "Score" },
  { username: "866612", password: "1M7DYQxL", agencyName: "DCC" },
  { username: "494950", password: "EVjpk4MO", agencyName: "Titans" },
  { username: "596834", password: "K4YHf51e", agencyName: "Maxxed Out Media" },
  { username: "558594", password: "7lVN9Xm1", agencyName: "SOLLA" },
  { username: "480752", password: "p0eNxP1y", agencyName: "Wahoo" },
  { username: "230386", password: "5GBj0Dmb", agencyName: "Stellar Ocean" },
  { username: "767809", password: "bU93MHob", agencyName: "Molila" },
  { username: "262344", password: "2aE3cA42", agencyName: "QR STUDIO" },
  { username: "572524", password: "vecXoyC4", agencyName: "BloomGirls Media" },
  { username: "923437", password: "hz3EH1b6", agencyName: "HAINA" },
  { username: "836030", password: "puSC47QR", agencyName: "On Socials Collective" },
  { username: "521593", password: "WRM1wQ4k", agencyName: "Zeitflix-DE" },
  { username: "661130", password: "Rs9SZ6JP", agencyName: "YI jing chuan mei" },
  { username: "796780", password: "CAfSC0ep", agencyName: "Kuujojo" },
  { username: "432583", password: "v58XJq3n", agencyName: "WIND DIRECTION" },
  { username: "699680", password: "8T6Qk4Je", agencyName: "X-OPTION AGENCY" },
  { username: "155779", password: "mX4Aa4Vq", agencyName: "Just Not" },
  { username: "432805", password: "91h7ebTy", agencyName: "Guangzhou Yanzun Trading Co  Ltd." },
  { username: "654094", password: "HZa7bDbT", agencyName: "The Affiliate Family" },
  { username: "391221", password: "ULSL1SgR", agencyName: "YIZOO" },
  { username: "678225", password: "JHbwiFH0", agencyName: "LON" },
  { username: "980697", password: "J2pMbPJ3", agencyName: "SPARK UK+" },
  { username: "248710", password: "k9PJU20O", agencyName: "Garcia Media" },
  { username: "892979", password: "S6taa7ZU", agencyName: "Starealm" },
  { username: "521509", password: "LvQZkP5e", agencyName: "Bamboo Digital" },
  { username: "344887", password: "lcKKfM6M", agencyName: "Brands Meet Creators" },
  { username: "335081", password: "GeAhcuh8", agencyName: "Inboostr - Digital Marketing" },
  { username: "621386", password: "1Hi16Y6d", agencyName: "Outlandish LIVE" },
  { username: "437970", password: "C6fqePWx", agencyName: "Turn-Key Studios" },
  { username: "540497", password: "u0h4dq5Q", agencyName: "APAXIC" },
  { username: "366267", password: "UD7WyuNc", agencyName: "Feng US" },
  { username: "240131", password: "K7abYo5e", agencyName: "Jiu Mo" },
  { username: "464336", password: "v7MXasmh", agencyName: "PAPAYASZ" },
  { username: "535815", password: "eAVZ0UMk", agencyName: "Bluemedia-us" },
  { username: "664909", password: "RqT7SseO", agencyName: "SparkCloud" },
  { username: "190319", password: "wun7Ne4J", agencyName: "IWinWorld" },
  { username: "671176", password: "bqaBZ0XH", agencyName: "MIGO Media" },
  { username: "339994", password: "XN6anFIZ", agencyName: "Musk-Fans" },
  { username: "393623", password: "hf8Nn2lV", agencyName: "The Empire Agency" },
  { username: "181161", password: "rv1sKViP", agencyName: "HOLA COMPRA MEDIOS" },
  { username: "708674", password: "Bsy7LkLO", agencyName: "THE GEEKY GREENS" },
  { username: "402160", password: "DzU2kc9m", agencyName: "Lively Global" },
  { username: "118302", password: "NNeFcki9", agencyName: "Sellery Talent" },
  { username: "141266", password: "E0D5fv40", agencyName: "BorderX Media" },
  { username: "203680", password: "IEt0YivA", agencyName: "GTMex" },
  { username: "275108", password: "Ql9Y4UQM", agencyName: "MLX" },
  { username: "782160", password: "5gOUIJN2", agencyName: "FuTing" },
  { username: "145435", password: "ORvPCVd1", agencyName: "live  spark" },
  { username: "850453", password: "PUY2Iny2", agencyName: "Unsociable" },
  { username: "685018", password: "GnGmKKn3", agencyName: "VibeLab" },
  { username: "437374", password: "FYCN28ii", agencyName: "IC" },
  { username: "173841", password: "N095BzhQ", agencyName: "cfactor" },
  { username: "199701", password: "JAUOqlM7", agencyName: "Papaya Given Agency" },
  { username: "453625", password: "vmyd8gEB", agencyName: "Black Core" },
  { username: "676210", password: "XSav33NL", agencyName: "0528 HOLDINGS" },
  { username: "481441", password: "hSxa4Rvo", agencyName: "RISE MCN" },
  { username: "553621", password: "8pe3qEM3", agencyName: "UMI" },
  { username: "510429", password: "ZNsmU52w", agencyName: "AFM Agency" },
  { username: "108057", password: "j8QFAopB", agencyName: "TAPTALK" },
  { username: "540563", password: "0FoZJqr1", agencyName: "Ed Hopkins PR" },
  { username: "758242", password: "kIyWgk5h", agencyName: "Spotlight Media" },
  { username: "225472", password: "x2l9uyIz", agencyName: "easygo" },
  { username: "313637", password: "p3IM8w5q", agencyName: "TIKLATAM" },
  { username: "157807", password: "lN6Xmv4V", agencyName: "Create Voyages" },
  { username: "618997", password: "XGwnXTL0", agencyName: "LAIGLE" },
  { username: "498000", password: "wp3TS9FF", agencyName: "Cloude" },
  { username: "783003", password: "DPzQq1jl", agencyName: "Moxymgt" },
  { username: "642619", password: "fMCbd0hv", agencyName: "NoAging.uk" },
  { username: "432835", password: "pRVkf950", agencyName: "GREAT  GROUP" },
  { username: "496790", password: "gXTl941d", agencyName: "Lo Digital Ecomm" },
  { username: "201243", password: "yb0d9YpB", agencyName: "Cora Media" },
  { username: "432523", password: "RiwhPK7q", agencyName: "ASANDY Media" },
  { username: "458654", password: "G23fovZE", agencyName: "Papaya Given Group" },
  { username: "538259", password: "27oju67N", agencyName: "Dream HQ" },
  { username: "210248", password: "WXtKD1Ru", agencyName: "Peerless Alliance" },
  { username: "597908", password: "yPI4546d", agencyName: "Kalowave US" },
  { username: "539777", password: "njDCU0if", agencyName: "Be Friends SSG US" },
  { username: "821848", password: "U8ConkrY", agencyName: "DST US" },
  { username: "787308", password: "fqfCz002", agencyName: "mintaura" },
  { username: "916755", password: "c61dVIAy", agencyName: "teleporting.nyc" },
  { username: "418101", password: "QUlfor8r", agencyName: "OWN" },
  { username: "645046", password: "It4if8Xc", agencyName: "BidaRabbit" },
  { username: "674485", password: "BCt8UjUX", agencyName: "FlyToTheMoon" },
  { username: "331966", password: "0LuJQmIl", agencyName: "US Starrank" },
  { username: "963915", password: "fmysR4GL", agencyName: "CL Studio" },
  { username: "581325", password: "qk303DwK", agencyName: "BaiTube USA" },
  { username: "829615", password: "e3555dGq", agencyName: "Xcxin" },
  { username: "288997", password: "o4Be7T3W", agencyName: "The Horizon X" },
  { username: "123066", password: "8RtgLu0m", agencyName: "Boqitok" },
  { username: "258158", password: "g1lvLuXI", agencyName: "MOCELL" },
  { username: "500589", password: "I2xuA2lu", agencyName: "Swavant" },
  { username: "757918", password: "3KHMOjB4", agencyName: "MSYIMPORTEDGE MEDIA" },
  { username: "275661", password: "ruERK3KV", agencyName: "D-Wave" },
  { username: "616154", password: "LW2GlJrd", agencyName: "NoAging.MX" },
  { username: "912549", password: "Xe0GT9hf", agencyName: "U&ME AGENCY" },
  { username: "846488", password: "sAcp8rmK", agencyName: "WGY Limited" },
  { username: "914658", password: "VqnFYT4d", agencyName: "Moos Agency" },
  { username: "260985", password: "ePx6TufF", agencyName: "ENTROPI USA" },
  { username: "920559", password: "mvj9W9Z3", agencyName: "Ruiyuan" },
  { username: "883201", password: "zb0atuUN", agencyName: "QIANFANJING" },
  { username: "854104", password: "yks8CT79", agencyName: "LOOZIIVET" },
  { username: "955384", password: "FZU9l62y", agencyName: "Outlandish UK" },
  { username: "891503", password: "c77nqsA0", agencyName: "MRE MEDIA" },
  { username: "803927", password: "M5ux69RK", agencyName: "Viral Peak Agency" },
  { username: "588551", password: "xMvBZmD9", agencyName: "YANGFAN" },
  { username: "821992", password: "xA1ZhU7U", agencyName: "Willin agency ES" },
  { username: "412033", password: "E5Yb9vXk", agencyName: "Ling Tap" },
  { username: "830589", password: "1AkCeFG3", agencyName: "Fynmemedia" },
  { username: "695179", password: "NVp3GSyM", agencyName: "SUN STORY" },
  { username: "976473", password: "Ox91wNFs", agencyName: "Xanadu" },
  { username: "612703", password: "j29PV6dA", agencyName: "LINGTO" },
  { username: "651929", password: "vATjJi0K", agencyName: "BIN FEN MCN" },
  { username: "616032", password: "1gJaNQ0K", agencyName: "JoyWave" },
  { username: "651138", password: "Rj3tAzR9", agencyName: "QQ Shop" },
  { username: "883312", password: "b0qcW5xx", agencyName: "DVDR" },
  { username: "736313", password: "ieVm3tBa", agencyName: "Grail Talent" },
  { username: "102576", password: "Ik7eZs0q", agencyName: "Realive TAP" },
  { username: "137450", password: "gQn7VjLh", agencyName: "AIEASYGO" },
  { username: "729603", password: "32QBtdMB", agencyName: "QTQI" },
  { username: "167543", password: "7a6HrMGy", agencyName: "WETOK" },
  { username: "867146", password: "un4FPizW", agencyName: "WHALE." },
  { username: "363031", password: "K7u1VAAV", agencyName: "Guli" },
  { username: "104193", password: "u2ge8rPP", agencyName: "OathDream" },
  { username: "115926", password: "gJ7EfbR0", agencyName: "MingYang" },
  { username: "292727", password: "dWIW4wi8", agencyName: "Canvas The Agency" },
  { username: "932421", password: "7vEpMJQL", agencyName: "wesale" },
  { username: "713018", password: "RN98zJv8", agencyName: "Hangzhou Pindai Brand Management Co., Ltd." },
  { username: "413832", password: "TdcCzU5P", agencyName: "MI" },
  { username: "732497", password: "2B3QKGr5", agencyName: "BXMedia" },
  { username: "329214", password: "y15QlnKq", agencyName: "Jingxing" },
  { username: "361400", password: "Gdd3EaOI", agencyName: "CreatoRev" },
  { username: "237570", password: "r09N6tAH", agencyName: "Think Loud" },
  { username: "460262", password: "yNVjF4Ew", agencyName: "SY TOP" },
  { username: "346047", password: "W66fg2L1", agencyName: "FingerSnap" },
  { username: "531251", password: "qrUj7zs8", agencyName: "Limitless Studios Inc." },
  { username: "875834", password: "ZC1Xp9Rm", agencyName: "INFound" },
  { username: "107153", password: "Dv5fSj8s", agencyName: "Pathway Agency LLC" },
  { username: "923285", password: "22CQcI2k", agencyName: "Media Consult, LLC" },
  { username: "196225", password: "9lnr9IpD", agencyName: "dingdun" },
  { username: "887354", password: "7S19LAUi", agencyName: "BOT VON FARMAND AGENCY" },
  { username: "654433", password: "eUKonT94", agencyName: "Simple Sauce Group" },
  { username: "948391", password: "9pF5aBiw", agencyName: "TOPEGG-TO" },
  { username: "109902", password: "CnG2AiLy", agencyName: "DTXH US" },
  { username: "189360", password: "5FIOoGki", agencyName: "YUE KE" },
  { username: "525393", password: "l8Rt1oIu", agencyName: "YCSMLTD" },
  { username: "587441", password: "RT26cTjk", agencyName: "QingNiao" },
  { username: "633746", password: "Wklv6n4S", agencyName: "Jiezi" },
  { username: "516332", password: "HL1jYKR9", agencyName: "VI CLIC" },
  { username: "139651", password: "Vx96ANMv", agencyName: "YKUNTECH" },
  { username: "891969", password: "iCjA8lz0", agencyName: "New Shiji" },
  { username: "716223", password: "UxjUzSw3", agencyName: "RAshmi" },
  { username: "856522", password: "gwxQd02U", agencyName: "RIVEGA INMOBILIARIA" },
  { username: "659485", password: "3m7XveCD", agencyName: "PDC Media" },
  { username: "428313", password: "o5eXLkvW", agencyName: "INFLUENCER CHAMBER" },
  { username: "245352", password: "n58DPrze", agencyName: "FUNFINE MEDIA US" },
  { username: "509846", password: "dtA0tGhf", agencyName: "NUOXIN" },
  { username: "785789", password: "Mnxk7Pbt", agencyName: "CreatorBonus by ShoppeDance Inc." },
  { username: "952850", password: "NeMpymG5", agencyName: "MliMli" },
  { username: "532555", password: "CfSP2MnS", agencyName: "San Deng" },
  { username: "431462", password: "t0m5sYDs", agencyName: "kosmarts" },
  { username: "866786", password: "7ZOyhH9j", agencyName: "CCA" },
  { username: "554985", password: "4RDH5xNk", agencyName: "Lanxi" },
  { username: "964167", password: "p7U9aQOs", agencyName: "Tourmaline" },
  { username: "354290", password: "pKtl5vqQ", agencyName: "DoumobMedia" },
  { username: "930441", password: "klFpm5pF", agencyName: "UGO Global Selling" },
  { username: "283689", password: "6F52Kho4", agencyName: "Vista" },
  { username: "144446", password: "2cVdmZkH", agencyName: "Tif Creative" },
  { username: "614577", password: "oGPy0Ol6", agencyName: "KuiB" },
  { username: "210244", password: "FYT7rx6n", agencyName: "WHALE.CULTURE" },
  { username: "725004", password: "C6Fb4OvR", agencyName: "Content Lab" },
  { username: "541093", password: "wLhfU0x9", agencyName: "Joy Media" },
  { username: "202961", password: "VcHzdr0a", agencyName: "Golden" },
  { username: "665197", password: "TRf6hgAz", agencyName: "Ideas" },
  { username: "198006", password: "l3dXuNZF", agencyName: "gate" },
  { username: "806929", password: "OhPF57WQ", agencyName: "T-art Digital DE" },
  { username: "596898", password: "0e2goS9r", agencyName: "KEY TT" },
  { username: "401748", password: "U9vsq3Fs", agencyName: "Titans UGC" },
  { username: "106927", password: "NkWBvl7w", agencyName: "Infinity Global Media" },
  { username: "273046", password: "1tYLsQFF", agencyName: "FENDA" },
  { username: "417875", password: "0zi2HwF1", agencyName: "PAP Mass Media" },
  { username: "719146", password: "ehX76bwA", agencyName: "Jdy management" },
  { username: "928818", password: "8WJ2gj4M", agencyName: "T Gen" },
  { username: "536534", password: "iT8S3UXi", agencyName: "MCN Iberia" },
  { username: "731620", password: "HV11Izek", agencyName: "Vortex Media" },
  { username: "745568", password: "yzHXij50", agencyName: "Summers EasyMedia" },
  { username: "103239", password: "d1vdIAvv", agencyName: "Commerce Social" },
  { username: "760881", password: "VB9dszkn", agencyName: "CARAVEL MEDIA" },
  { username: "554281", password: "ga4JNwdR", agencyName: "JOVE UK" },
  { username: "950536", password: "3SpwhZlB", agencyName: "TRUST NETWORK" },
  { username: "313560", password: "w0wWO1sg", agencyName: "Famfluence Affiliate agency" },
  { username: "622964", password: "sjiZ9uof", agencyName: "Dimension 6" },
  { username: "379756", password: "N9QQf2w3", agencyName: "Tank Top Agency" },
  { username: "171861", password: "UthOTY7Q", agencyName: "GEN Z GROUP" },
  { username: "796490", password: "2ceEE84q", agencyName: "Red Harp" },
  { username: "458457", password: "WnSYv69w", agencyName: "INLY MEDIA USA" },
  { username: "855361", password: "ImfGnIm7", agencyName: "COMMERCIAL GROUP & IMPORTS DEMAZ" },
  { username: "405770", password: "gk6iOyET", agencyName: "OOIN MEDIA" },
  { username: "461953", password: "Qds8NTKP", agencyName: "Trendii Talent DE" },
  { username: "987864", password: "Th7i8eCd", agencyName: "Live and Vibrant" },
  { username: "207540", password: "SyQd6OHm", agencyName: "THINKERAS" },
  { username: "739874", password: "JhdArJ9W", agencyName: "Hongyue Technology" },
  { username: "641126", password: "4FchbrFV", agencyName: "MagicInfinite" },
  { username: "143688", password: "ZKXI0ycW", agencyName: "Style Sphere" },
  { username: "709403", password: "K6cKlR3I", agencyName: "Flyfish" },
  { username: "739202", password: "sqa4F57Y", agencyName: "Chong Xiao Wu" },
  { username: "152103", password: "9WxJmTvL", agencyName: "Dream Bay Group" },
  { username: "111114", password: "rgzF6JL8", agencyName: "DRI" },
  { username: "838881", password: "q87OiiGC", agencyName: "Adtoker Europe" },
  { username: "232550", password: "Ph5o2BDb", agencyName: "CreatorCore" },
  { username: "156161", password: "jVFxsV01", agencyName: "BSLM" },
  { username: "576246", password: "3JF7QNo1", agencyName: "SAMRAAT Network" },
  { username: "633792", password: "0JA75nD2", agencyName: "Qiya Technology" },
  { username: "883141", password: "btnB1fC7", agencyName: "Aequora" },
  { username: "534991", password: "J1zO8GhB", agencyName: "echooma" },
  { username: "865894", password: "Bz7ldI5p", agencyName: "We Marketing" },
  { username: "764787", password: "xRDMiOU7", agencyName: "pp joy" },
  { username: "619252", password: "7N9zsVXf", agencyName: "Wayward" },
  { username: "691961", password: "Ya4OVcJ0", agencyName: "LKCX.Media" },
  { username: "941150", password: "5A97eZgX", agencyName: "Social Commerce Club" },
  { username: "756028", password: "6GWwwq8R", agencyName: "Affiliate Automated" },
  { username: "242300", password: "39Un9vzp", agencyName: "Yowant US" },
  { username: "848039", password: "pysvC1gL", agencyName: "Aotuosi" },
  { username: "872152", password: "SZoy0e5O", agencyName: "Western Boys" },
  { username: "664898", password: "id4J1oPl", agencyName: "TCA UK" },
  { username: "363435", password: "d4SaPXAl", agencyName: "K-veri" },
  { username: "282280", password: "F8pnIt2u", agencyName: "DTTLY" },
  { username: "704418", password: "fSc0Zhta", agencyName: "907 Media LLC" },
  { username: "534079", password: "wJW2OF55", agencyName: "forest us" },
  { username: "959433", password: "nJdc65DO", agencyName: "weiyuan" },
  { username: "337089", password: "5qO68Moj", agencyName: "CHATTK" },
  { username: "455184", password: "Mcx57NQ1", agencyName: "Zhuo Hai" },
  { username: "719677", password: "3lL1kTrK", agencyName: "Hieye" },
  { username: "429376", password: "fqVz9TjO", agencyName: "Z&H" },
  { username: "545661", password: "KcbHtwt6", agencyName: "Toyonet MX" },
  { username: "518790", password: "fCNZg8U8", agencyName: "WONIU_Global" },
  { username: "695722", password: "rg9lwTOE", agencyName: "AMMI" },
  { username: "333607", password: "FxY33Bya", agencyName: "Live Academy" },
  { username: "954004", password: "v1J0AR5u", agencyName: "CREATIVA CLUB LLC" },
  { username: "794272", password: "24beKf98", agencyName: "HAR" },
  { username: "420850", password: "W4Ofilrm", agencyName: "BOOST US" },
  { username: "863445", password: "MiVB1k3M", agencyName: "yaochen" },
  { username: "359748", password: "YZjCts70", agencyName: "YOWANT NETWORK" },
  { username: "772751", password: "jICp0Gk7", agencyName: "Shoplooks" },
  { username: "240644", password: "JJRt7eYb", agencyName: "HEMU" },
  { username: "192192", password: "4aKbWFWp", agencyName: "JingHui E-commerce" },
  { username: "852964", password: "R5iL4LbG", agencyName: "KKisland" },
  { username: "443468", password: "N3gsYwW7", agencyName: "Bluetopia" },
  { username: "170677", password: "KV1vdoYT", agencyName: "Flutter Labs LLC" },
  { username: "273257", password: "OgyuXJm6", agencyName: "Mother Shoppin Partnership" },
  { username: "490606", password: "XBG0vQnb", agencyName: "DELICIOUSFAST" },
  { username: "512517", password: "S5H0eFar", agencyName: "HENGxiangUS" },
  { username: "249621", password: "54NvKQb2", agencyName: "LOTTO" },
  { username: "744846", password: "7upRBsVl", agencyName: "Greenliv" },
  { username: "606475", password: "8ouIUK7Z", agencyName: "Koala & Tree" },
  { username: "882966", password: "RmYD0jfT", agencyName: "Starry*" },
  { username: "917843", password: "7fNNnm3W", agencyName: "Sparkling ES" },
  { username: "618538", password: "5f96OiLy", agencyName: "KEYWEB AGENCY" },
  { username: "997476", password: "4Phq9MmZ", agencyName: "GAXI" },
  { username: "162329", password: "k9b4zfUL", agencyName: "YEAH FANS SOLUTIONS" },
  { username: "514897", password: "9VzYuEln", agencyName: "Force Awakens" },
  { username: "280189", password: "Qg8c1P3s", agencyName: "TourMateCN" },
  { username: "909139", password: "14JPuzue", agencyName: "A-List Me" },
  { username: "631751", password: "sJy8kXAW", agencyName: "Goya" },
  { username: "372486", password: "gQJGtrz6", agencyName: "infiniite" },
  { username: "820754", password: "TItc5Ukd", agencyName: "LightBulb Live" },
  { username: "731046", password: "lJ3spCnL", agencyName: "TIKLATAM USA" },
  { username: "299615", password: "hpv40w8V", agencyName: "weiruistrong" },
  { username: "959205", password: "LTDYn8rw", agencyName: "TELLING CLUB" },
  { username: "811372", password: "qVO5G2lb", agencyName: "BIAOSHENG" },
  { username: "290337", password: "yZ8RKgDU", agencyName: "Whale Leap Star Path" },
  { username: "345542", password: "5Wh6VymQ", agencyName: "MuseAI" },
  { username: "979740", password: "12Xpk9Sn", agencyName: "drice" },
  { username: "519855", password: "5ckMXC5Q", agencyName: "Creator's Corner" },
  { username: "461614", password: "mpp3tUYG", agencyName: "COMU US" },
  { username: "348856", password: "T3hPJv3r", agencyName: "XIYOUFUN" },
  { username: "170958", password: "i51BS1p1", agencyName: "Solaris League" },
  { username: "392197", password: "w0otSHPZ", agencyName: "YONO" },
  { username: "231024", password: "lq3UbwAT", agencyName: "Affiniti Studios" },
  { username: "868124", password: "XAzL0Kmv", agencyName: "NoAging fr" },
  { username: "425512", password: "83UbErZG", agencyName: "456 Growth" },
  { username: "520766", password: "a6sAWq8K", agencyName: "STZC" },
  { username: "720218", password: "wMb2RMJ6", agencyName: "Ravyn" },
  { username: "433213", password: "7E9tkLHR", agencyName: "Iris Rising" },
  { username: "844736", password: "UMwUU4Zo", agencyName: "GEEKO" },
  { username: "629893", password: "YR0uVRK4", agencyName: "greenorange" },
  { username: "352772", password: "i3MUKt5d", agencyName: "NUTS_" },
  { username: "745117", password: "AqcAGS6s", agencyName: "MAXWELL STUDIOS" },
  { username: "521712", password: "LlK1Tv4V", agencyName: "FAITHFLUENCE" },
  { username: "857461", password: "ynM16Dre", agencyName: "Toothbuckle Agency" },
  { username: "352717", password: "ytSxR1AK", agencyName: "Inprint Interactive" },
  { username: "886318", password: "5L8FewSB", agencyName: "Timeless Legacy" },
  { username: "411611", password: "d3CE5Q8t", agencyName: "FMKJ-UK" },
  { username: "487884", password: "4T6Dl9je", agencyName: "Creatify" },
  { username: "117581", password: "LbgtH9IN", agencyName: "PIGGYPAYUS" },
  { username: "289856", password: "4bSlELcC", agencyName: "Reach Digital" },
  { username: "402172", password: "iJnR4W9M", agencyName: "Pence Creators" },
  { username: "629987", password: "0QM9KXqo", agencyName: "Represent PR" },
  { username: "499250", password: "mSktw14q", agencyName: "PEIPEINYC" },
  { username: "118693", password: "vP5i16ay", agencyName: "FTTV" },
  { username: "534191", password: "AcWg0naO", agencyName: "Bocen Media MX" },
  { username: "947367", password: "V34fsA6P", agencyName: "ANDVIDS" },
  { username: "805927", password: "wRl3TbPN", agencyName: "SK_shuaiku" },
  { username: "895385", password: "7ZuP4RRa", agencyName: "NBCN LATAM, S. DE R.L. DE C.V." },
  { username: "966039", password: "9KFRCg4N", agencyName: "Miyaiscie Influencer" },
  { username: "829101", password: "mjbaK7VD", agencyName: "sunnymedia" },
  { username: "760458", password: "rLMX7FsB", agencyName: "Honey Drip Creators" },
  { username: "143089", password: "NFMb2Rv6", agencyName: "POWER OF BELIEVE" },
  { username: "998958", password: "sGGixu23", agencyName: "Hamburger" },
  { username: "513670", password: "lMM7zHyl", agencyName: "Binsen" },
  { username: "442733", password: "cwK1aWIp", agencyName: "Vogue Rader" },
  { username: "468880", password: "Acs0oQPm", agencyName: "Xingyi Plan" },
  { username: "233328", password: "Hxt5eo0P", agencyName: "CreatorBonus by ShoppeDance" },
  { username: "391023", password: "2OL7OAy0", agencyName: "SANSU" },
  { username: "354484", password: "qwFgBM73", agencyName: "Memo Mexico" },
  { username: "427637", password: "E0iBFLlX", agencyName: "Papaya Given" },
  { username: "622038", password: "GiLI02Gx", agencyName: "saniversumm" },
  { username: "394675", password: "mvKS7CYr", agencyName: "Pretty Center" },
  { username: "656265", password: "hPBVTtk0", agencyName: "Lumen Edge" },
  { username: "550969", password: "8C8NU43c", agencyName: "YOUNGGUNS ENT SHOP" },
  { username: "837799", password: "X0TWzqPI", agencyName: "Passion J" },
  { username: "927859", password: "E04pfOPU", agencyName: "Avocado DE" },
  { username: "439043", password: "xG8kuSk3", agencyName: "FREEDOM WIND" },
  { username: "623077", password: "YKxNv2D0", agencyName: "U.M.T US" },
  { username: "178615", password: "Ca0kbuef", agencyName: "The Creator Loop" },
  { username: "236662", password: "6L6uicMT", agencyName: "BlueBag.CN" },
  { username: "253022", password: "Cia9lYkl", agencyName: "Hangzhou Kangjun Health Management Consulting Co., Ltd" },
  { username: "167449", password: "oH59vNE2", agencyName: "SuperOrdinary USA" },
  { username: "666084", password: "FM96ep2K", agencyName: "Outlandish US" },
  { username: "609966", password: "rQ0XsbOh", agencyName: "BuyCoolBeans" },
  { username: "274872", password: "Iyv6UDKP", agencyName: "ZS" },
  { username: "736543", password: "A82F2zv2", agencyName: "Sun and Sky Entertainment" },
  { username: "936191", password: "e2vF0oYq", agencyName: "Avocado US" },
  { username: "713206", password: "4nuY3Yie", agencyName: "VibraVerse MX" },
  { username: "594612", password: "Y9KXzPSy", agencyName: "SDHH" },
  { username: "515444", password: "pT3Kei3O", agencyName: "Clifton Media" },
  { username: "228438", password: "P2bTTN7J", agencyName: "PROPE" },
  { username: "710954", password: "rp477FIq", agencyName: "shiying-fashion" },
  { username: "471442", password: "U0MpTrPl", agencyName: "Jiahang Media" },
  { username: "595339", password: "3JMn4vYd", agencyName: "Iffert Media LLC" },
  { username: "821849", password: "ZJ5o6qNH", agencyName: "Ninup" },
  { username: "371156", password: "7cLFQz3E", agencyName: "LUNAHOLM US" },
  { username: "134365", password: "yqFbi3Tb", agencyName: "YZ" },
  { username: "710629", password: "nw4M83tk", agencyName: "GPL" },
  { username: "165182", password: "9ytgH6gZ", agencyName: "Holmburgh" },
  { username: "904177", password: "k82TBBc9", agencyName: "xlg start shop" },
  { username: "308064", password: "3qZKy4Bs", agencyName: "Shanmu Media" },
  { username: "447013", password: "ejKMnV4E", agencyName: "VIKOC LLC" },
  { username: "694152", password: "8nnI4icS", agencyName: "TDV" },
  { username: "768075", password: "rSCk8Cb4", agencyName: "fleet" },
  { username: "391491", password: "Ukt4vAfT", agencyName: "Woke Network" },
  { username: "987856", password: "dsklVrr5", agencyName: "Xingxin Media" },
  { username: "440508", password: "kfGtQ5eq", agencyName: "Bonjour 4C" },
  { username: "387983", password: "XCg1I23p", agencyName: "Join Brands" },
  { username: "232197", password: "0TbyXg3o", agencyName: "VICTORY INTERNATIONAL GROUP" },
  { username: "899013", password: "26E0AJYg", agencyName: "DorLene" },
  { username: "138274", password: "Hkj1fvLg", agencyName: "SinoClick US" },
  { username: "387714", password: "jY6NZfny", agencyName: "Ote MCN" },
  { username: "693856", password: "GhpKSw8E", agencyName: "Bainiao" },
  { username: "927771", password: "7rlcxOK0", agencyName: "CloudMorn" },
  { username: "230737", password: "BSsXpad9", agencyName: "Dream Building" },
  { username: "552732", password: "5hKH2adr", agencyName: "VHGROUP" },
  { username: "208066", password: "mMULKVa0", agencyName: "Befriends usa" },
  { username: "437484", password: "vuQjn8JX", agencyName: "YUNSHI MCN" },
  { username: "411821", password: "0fFDzUXK", agencyName: "1 Second" },
  { username: "242885", password: "Tv3XK1fw", agencyName: "Befriends MEDIA" },
  { username: "857722", password: "p3axUGw5", agencyName: "Rough Seas" },
  { username: "407238", password: "Ux63QTC7", agencyName: "WUYEJI" },
  { username: "761293", password: "0butNNJB", agencyName: "Luffy Media" },
  { username: "336874", password: "rKoY9iAt", agencyName: "MAX INTERNATIONAL" },
  { username: "449267", password: "L5jeW0Wp", agencyName: "Star Creators" },
  { username: "333971", password: "9t5F641H", agencyName: "Digital Third Rock Media, Inc." },
  { username: "400508", password: "5jktXm0Z", agencyName: "IceSpear" },
  { username: "899371", password: "XuWkarD2", agencyName: "Greatflowerus" },
  { username: "917401", password: "jB2zmrwN", agencyName: "Ye Lab" },
  { username: "161984", password: "YKlL7rAZ", agencyName: "ENKIME" },
  { username: "239377", password: "ROI174Vy", agencyName: "Roots Marketing Agency" },
  { username: "466175", password: "99ohQ4HH", agencyName: "Avocado" },
  { username: "735307", password: "5XtK9LMx", agencyName: "Force Awakens MCN" },
  { username: "791735", password: "F8hNxcVv", agencyName: "Unity Media" },
  { username: "658006", password: "kUwGxJ2U", agencyName: "Drakon" },
  { username: "139422", password: "whvF8nL5", agencyName: "Creator Depot Shop Agency" },
  { username: "899759", password: "u4QrobqO", agencyName: "Classic  Media" },
  { username: "683390", password: "6HaZHRlG", agencyName: "MEDIGLPE" },
  { username: "941581", password: "Ruk4Blk0", agencyName: "NewStar_US" },
  { username: "243553", password: "4l9AF4YA", agencyName: "Efluencer" },
  { username: "707750", password: "ePWv0wl4", agencyName: "Bigs cat" },
  { username: "741783", password: "bGcG2qp9", agencyName: "Blue Whale Media" },
  { username: "216952", password: "kgaCQrK9", agencyName: "JAXE" },
  { username: "628727", password: "WJsJm56S", agencyName: "GreenWood MCN" },
  { username: "861148", password: "84bDVjH1", agencyName: "SHUPINTECHNOLOGY" },
  { username: "709238", password: "h6Bavez6", agencyName: "VansinoNetwork" },
  { username: "372666", password: "SbO5x0Vz", agencyName: "Boundless MGMT" },
  { username: "686770", password: "trU7CgJF", agencyName: "maze us" },
  { username: "155721", password: "T4DsfPr8", agencyName: "UnityWave" },
  { username: "281348", password: "ST2fA6lH", agencyName: "Evolution" },
  { username: "309601", password: "vysjQe8z", agencyName: "Joanna&Eleven" },
  { username: "627769", password: "b6HFaC67", agencyName: "MIYUKI" },
  { username: "938279", password: "XhGy3jye", agencyName: "RIGHT WORK" },
  { username: "659543", password: "M10NfZUB", agencyName: "Marketinglama" },
  { username: "613339", password: "t5XcbArm", agencyName: "JW-TAP" },
  { username: "141960", password: "jOW9WEp4", agencyName: "Pattern US" },
  { username: "683850", password: "ZJ94oyI7", agencyName: "OUMEIHUI media" },
  { username: "921636", password: "Pc990l4y", agencyName: "Foreversea US" },
  { username: "699542", password: "0Or7aQtA", agencyName: "Yean" },
  { username: "750860", password: "AHp4WQui", agencyName: "Qian fan  Cross-border" },
  { username: "492002", password: "4Ii6XW6b", agencyName: "Nat Pack Nation" },
  { username: "613318", password: "kDqG34nv", agencyName: "BJ QMZX" },
  { username: "601904", password: "3bpPpu6A", agencyName: "Evergreen" },
  { username: "865420", password: "jEBKp5A2", agencyName: "BIG SKY TOWING" },
  { username: "519450", password: "oz8E5yL0", agencyName: "Lucky Focus" },
  { username: "147371", password: "U7Ze4Zc9", agencyName: "New Beginnings Agency" },
  { username: "168411", password: "RkVwDpL8", agencyName: "QIWEIMEDIA" },
  { username: "809880", password: "Pa0TLd7Z", agencyName: "BoBoMedia" },
  { username: "632861", password: "3KQCtN7V", agencyName: "OANNY FASHION" },
  { username: "145115", password: "FPwuxn07", agencyName: "InfluenceBridge" },
  { username: "649004", password: "fFTeyaD4", agencyName: "NULL" },
  { username: "651564", password: "GDQlH6hm", agencyName: "Total总计" },
  { username: "702126", password: "0Cn563tA", agencyName: "CJ Media" },
  { username: "385411", password: "olduSu2Y", agencyName: "MaGo-Force" },
  { username: "145813", password: "xYG0KXiG", agencyName: "Meiyang MX" },
  { username: "306250", password: "QE1VeyQd", agencyName: "Windboss" },
  { username: "585266", password: "B0AjH2IV", agencyName: "itsumo.inc (Peace Creation)" },
  { username: "330090", password: "0xIwBrZ2", agencyName: "LIVE COMMERCE JAPAN (LCJ)" },
  { username: "742512", password: "XgQ6C6sD", agencyName: "Fisherrni" },
  { username: "306991", password: "6K9llhrV", agencyName: "GZTIANFU" },
  { username: "667744", password: "aYZ9Os1b", agencyName: "Live Spark" },
  { username: "847209", password: "0viYYDkD", agencyName: "XiaoXi Culture" },
  { username: "823586", password: "TmZo3Vv2", agencyName: "JiangXi Mars" },
  { username: "201548", password: "VhJCo84m", agencyName: "starfuse" },
];

// ===== 机构名称列表（用于设置页搜索选择）=====
const AGENCIES = ["Yi Yao", "FJ ruixing", "QIDIAN", "JILIANG", "Longwen", "TZ", "Lefundo", "xumao31", "NVWA", "taoyi", "TT MEDIA", "WanHuateng", "haotian123", "7colors", "HUIYUE", "SEA IDEAL", "AY media", "Viva Media", "Bright forest", "DragonFlag", "xinba", "HAIJI", "LANDUN", "HANGBEI", "WAYMAX GLOBAL", "2739 Agency", "Global Press", "Adoredisc", "anyStarr US", "qianyuan", "JINGFAN", "The Alps Us", "WHALE.US", "TTS GLOBAL", "BESTHOMEGOODS", "MTOP", "Ice Emperor", "CM", "TFOP", "SUPERNOVA DIGITAL MEDIA UK LTD", "OBLIQ", "Three Pandas", "Anran E-commerce Studio", "Black flame cultural  media", "Tide", "BALEMBA", "yixing", "LION", "DOUBIAO", "NEXTGEN INFLUENCER", "TrendLab Media", "VIPStreamers Global", "Xanadu Global", "zoco", "HonestCreators", "MITURE", "The Alps Media", "Leixin mx", "Shenzhen Pennitech Co. Ltd", "MmDCT", "BJN", "STARLIVEMEDIA", "FOYOO", "WEAVEX", "Infinity Media Global", "Qingdao CSUP ENSI Education Co., Ltd.", "BEIJING DING'S YISION MEDIA CO.LTD", "GREEN MOVEMENT FUTURE", "AICENTERPRISE", "fyy", "BESTSELLER", "lanchuang", "Creatorflow", "Horizon Media", "KIM", "xinruizhi", "Starry-F", "SANYOU", "Lantronix", "GANYU", "EnergeticeGolobal", "TESSERACT", "TPGold", "Qianning", "AstraZ-MX", "SALC", "Flair MGMT", "WOTOHUB", "HARMONIOUSCOOPERATION MEDIA", "zcong", "PAIER", "BLUETRON", "YoungCare", "AMX MEDIA", "NOVATOK LTD", "VibraVerse", "TOP US", "HHT", "Leixin us", "NJ", "ZATEC", "FREE", "KnowDo", "Black Flame", "YunTo", "Social Army", "StarryHive", "WKZS Media", "DL2", "UN CO", "RoseRoot", "xiang tan wei lan", "NWS US", "GaoHua", "Wahool Shop", "Trutonic Media", "Katrina DiMiele LLC", "HENGFU", "The Inner Circle", "The Alps UK", "TABOOST", "GreenRipple", "FuRise", "jinghang", "Venus", "I.F. CONCEPT LTD", "ViralWave", "STONDA", "XTFOPTOK", "Puff Media Group Inc", "Sellery", "ZhongTong", "Tendencia Vestir MX", "FOR CHRIST", "DALE'S PIANO", "CLEMGO", "youmihuanjing", "ShanHai.QIJI", "XIYU", "shiying", "Creatok", "Mesoo", "The Alps MX", "VIPStreamers GS", "Fashion Tap Collective", "YH.UK", "pieasant", "SPARK", "CRFTOPUK", "CreatoRev Corporation", "JOMO", "MCN Iberia, SL", "Wesconnex.UK", "XTD", "Liveology US", "YQ", "zhizileye", "Starpavilion", "TFINE", "MUNI", "ZANXU", "MX", "Shinetree", "The Palette Network", "Super Fancy Squad US", "The Andes", "AstraZ", "SELLERY CAP", "MediaLabs", "YIYO Intl", "DecisionAI, Inc.", "HUAXIA", "SLEIPRE", "etop", "OU", "Lumosland", "jikeying", "Far Ahead", "HDH MEDIA", "PGG", "PRYME", "SIFANG", "Taplike", "letgoMX", "I.F. CONCEPT DE", "The Vanguard", "Junjie Cross-Border", "MINTRON", "Youla", "THE BRAINZ", "XPSTART", "TFOPEU", "Sparkling", "DIGNITY DENVER", "TTX media", "The Brainz IT", "Hojumbo Media", "SoCo", "SWAN MEDIA", "The Alps EU", "CreatorEmpire", "Global Trade US", "sunrise cross", "KLM", "Telepathy MCN", "WAN LIN", "HAIYING", "Jiuyiyuan", "DA DREAM", "WUHAN STAR", "KENNEY", "Influu", "Aode", "FLZ Union", "FireWeed", "Hoshihide", "Black Flame MX", "TIMEGO", "Kawaii Agency", "Set sail for distant trade", "PIGGYPAY-JP", "Lingxu Trading", "t-spot", "Gemdrop", "ruigoukuajing", "Huixing cross-border", "Thundrr", "StarRay Media", "fireweed EU", "OneTrust", "KFD", "KYRAN ZINEX", "Faith Howard", "Ju Zi MIDEA 3", "10th Mountain Lacrosse, Inc", "taihua", "JBT", "Meg Taylo", "Star Orange", "Liveology UK", "mulstars", "MiaoYu", "Yalian", "yi jing chuan mei one", "Gole-guli", "Fission", "UMU", "Lefundo Mexico", "Keshundi", "Addienix Digital Media", "StarLink Ltd", "See Hope", "AppicPlay", "XIBI", "SANEC", "lavenderwind", "MAAUS", "BAOHE", "GULFLIN", "GT MCN", "YH.US", "CANTON", "DB", "MomentiQ", "Gmart", "DawnRay", "WiseSurge", "seisa", "Bocen Media", "LI TRADE LTD", "AFFILINATION", "HTH", "Liyun", "CreationDose Srl SB", "Lei Xin", "Star Map", "ZING LAB", "UTrend", "KESOIL", "ATLAS", "xinyue", "Miture De", "Rs media", "PLUX", "Forstars", "SPACE DANCE", "HongShuo-", "butter", "Guangzhou Xingliang Network Technology Co", "Dongguan Maixiang Hardware Products Co., Ltd.", "Plain sailing", "Lefundo Studio", "handlababy_xx", "Star Fusion", "Elephant Media", "YINGGUO", "TuoLiDi", "SHENZHEN YUEWEN NETWORK TECHNOLOGY CO., LTD", "PrettiGoodz", "JIANGDONG MEDIA", "partheamedia", "XINGXING.Media", "qian hong", "Uango", "UNVSTAR", "KFisher", "WEILAN", "DXX", "TNTU", "EllaGrace", "A Dream", "LINGS", "HAIPAI", "MEIX", "STAR GROOP LTD", "LumaLink", "SWIER", "Media Production", "AquaPulse", "FBOP", "LiveTop Media", "Quanzhouwanwan", "BounceVerse", "TAILE", "ForStar", "KAIKAI NETWORK", "TecDo Hong Kong Limited", "NEXTPOP", "WMedia", "hongyun.Mea", "SPARK UK", "Cora", "CHQ Agency", "WUYUAN", "X S D", "ENGOOD", "AuroraX Media", "CHECK AZUL MEDIA", "Aura Digital Solutions", "THROUGH ONE", "fyyk", "Hua Yuan", "JYKJ8", "Giame Creator Collective", "Charm", "YYS", "MAXisMore", "Jingli", "JuGeEnergy", "Apex Media", "Supernova Ddigital", "T-ART", "CMRL", "Creative Fun UK", "fat head fish", "Influence Assembly", "GANCE", "XMYH", "Orri Hub", "DingLI", "WISHFUL TAP", "aifenxiang", "Lais MediaAB", "All-star", "Starry", "SellSpree", "MRONOS", "Avorio Cultura", "AFFINITY . MEDIA", "TMMB", "baoli", "MAIJIN", "ProHive", "Guangzhou Jinyang E-Commerce Co., Ltd", "JZ One", "OK ARE YOU", "TaiGu Media", "Yako", "Qi ming", "YooFinds", "JK", "SHENSI", "ZHIYANTK", "FirstLaunch  TAP", "JOMO Media", "CROSS YOUNG", "XINIU", "Rockies", "SPARK+", "EasyMedia", "TIANBOLUN", "CarterPulse", "GGREEN TRADE", "CREATOOR", "TimeChasing", "OUTLIER.", "TONGQIKUAJING", "Rowan Tech", "NOW PLAN", "Take-Copter", "Huaiaer", "Free Eagle", "FullMind Media", "The Brainz MX", "stellarseek es", "SHENZHEN HUIFU ADVERTISING DESIGN CO., LTD", "On Impacts", "The Brainz Global", "enjoyholiday", "sanhang", "LUNAHOLM", "HOTSALE", "Kevin E-commerce", "SFLIFUYHJII LLC", "PrimePicks", "YX", "Foreversea UK", "BORG RISE", "P2P Agency", "QZteam", "blue shark", "Go ashore", "JINNIUHUI", "youdianniudianshang", "Deg Lin", "Mainland MCN Consulting", "bingrun", "Elowen", "KawaStudio", "chaolian media", "Memo USA", "SLDZCN", "Wavegen Marketing UK", "FISH", "CHC Fashion Group US", "Wild Fire", "DOME SKY", "Zmingsi&ZMSMedia.", "Yangda Alliance", "influu USA", "Social Army MX", "Everest Group", "LAPA.uk", "yinlangchuanmei", "SYN FAMECOMMS", "puff media", "Pegasusus", "YH.MEX", "score US", "Goumee Tech", "Now Amuse", "Boosteo", "Creatorev Mexico", "LAPA-BYS", "PUYAN", "UVW", "DIAURA AGENCY", "NextWave", "Twee", "stacy", "Trove Land", "NAMIZU", "zeka", "CreatoRev UK", "MIMIMIAO", "Mediamz US", "CHINHO US", "4Creatorz", "Yunnan Maijia International Import and Export Co., Ltd.", "ViralWave_UK", "WHHK", "X-PRO LLC", "Famous creators media", "Grail", "Liancheng International", "42 TALENT AGENCY", "senbo", "jianjuansha", "SZMXFW", "TapTap", "AIT", "FOXLOLYUK", "SYMS", "Gmart-MXN", "HTS Group", "Burst", "SAICHU", "NoAging.IT", "VibraVers_SP", "Qibang", "Imprint Interactive", "Laixiu", "beeg1", "QiYi Online Media", "HEAVEN", "TokSurge", "Trend Spot", "VibraVers FR", "Sellery Spain", "Media Publishers LLC", "WOTOHUB LIMITED", "BlueVelvet", "TT Media EU", "VibraVers GM", "WANXIAO", "XINGLIU", "SUN Entertainmont", "Xinchuang", "SailsLink Ltd", "OrangePeel", "FNPWR", "IR Creartor", "TTY Technology", "xingze", "URL genius", "sunrise cross-border", "TTG", "The Fast Track Girl", "Tabletop Media", "LA ATUNERIA DE LOS CURRICANES", "Toplus", "DOULINK", "Live Legion", "Northern Media", "Starshine Creative", "Outlandish Digital Spain", "Euka", "TikMarketing", "SailingMedia", "LUNAHOLM MCN", "MSHP LAB", "IMX", "HSWang", "XSTREAM", "SMITH TRADING LLC", "I.F. CONCEPT", "5x Dashboard", "IcedOut MCN", "xinghangshijie", "alkamest", "Boost Engine", "Media Company", "LONDON AGENCY", "ShineTiger", "HLSW", "Master TV MCN", "ShopliveX", "BLUE SHIJIE", "D4N Creator Network", "Blue Bat Cafe", "Shang Jie", "VastOcean", "YUE FENG WEN HUA", "Pinteng", "zx", "Ordient Network", "Amireux", "Score", "DCC", "Titans", "Maxxed Out Media", "SOLLA", "Wahoo", "Stellar Ocean", "Molila", "QR STUDIO", "BloomGirls Media", "HAINA", "On Socials Collective", "Zeitflix-DE", "YI jing chuan mei", "Kuujojo", "WIND DIRECTION", "X-OPTION AGENCY", "Just Not", "Guangzhou Yanzun Trading Co  Ltd.", "The Affiliate Family", "YIZOO", "LON", "SPARK UK+", "Garcia Media", "Starealm", "Bamboo Digital", "Brands Meet Creators", "Inboostr - Digital Marketing", "Outlandish LIVE", "Turn-Key Studios", "APAXIC", "Feng US", "Jiu Mo", "PAPAYASZ", "Bluemedia-us", "SparkCloud", "IWinWorld", "MIGO Media", "Musk-Fans", "The Empire Agency", "HOLA COMPRA MEDIOS", "THE GEEKY GREENS", "Lively Global", "Sellery Talent", "BorderX Media", "GTMex", "MLX", "FuTing", "live  spark", "Unsociable", "VibeLab", "IC", "cfactor", "Papaya Given Agency", "Black Core", "0528 HOLDINGS", "RISE MCN", "UMI", "AFM Agency", "TAPTALK", "Ed Hopkins PR", "Spotlight Media", "easygo", "TIKLATAM", "Create Voyages", "LAIGLE", "Cloude", "Moxymgt", "NoAging.uk", "GREAT  GROUP", "Lo Digital Ecomm", "Cora Media", "ASANDY Media", "Papaya Given Group", "Dream HQ", "Peerless Alliance", "Kalowave US", "Be Friends SSG US", "DST US", "mintaura", "teleporting.nyc", "OWN", "BidaRabbit", "FlyToTheMoon", "US Starrank", "CL Studio", "BaiTube USA", "Xcxin", "The Horizon X", "Boqitok", "MOCELL", "Swavant", "MSYIMPORTEDGE MEDIA", "D-Wave", "NoAging.MX", "U&ME AGENCY", "WGY Limited", "Moos Agency", "ENTROPI USA", "Ruiyuan", "QIANFANJING", "LOOZIIVET", "Outlandish UK", "MRE MEDIA", "Viral Peak Agency", "YANGFAN", "Willin agency ES", "Ling Tap", "Fynmemedia", "SUN STORY", "Xanadu", "LINGTO", "BIN FEN MCN", "JoyWave", "QQ Shop", "DVDR", "Grail Talent", "Realive TAP", "AIEASYGO", "QTQI", "WETOK", "WHALE.", "Guli", "OathDream", "MingYang", "Canvas The Agency", "wesale", "Hangzhou Pindai Brand Management Co., Ltd.", "MI", "BXMedia", "Jingxing", "CreatoRev", "Think Loud", "SY TOP", "FingerSnap", "Limitless Studios Inc.", "INFound", "Pathway Agency LLC", "Media Consult, LLC", "dingdun", "BOT VON FARMAND AGENCY", "Simple Sauce Group", "TOPEGG-TO", "DTXH US", "YUE KE", "YCSMLTD", "QingNiao", "Jiezi", "VI CLIC", "YKUNTECH", "New Shiji", "RAshmi", "RIVEGA INMOBILIARIA", "PDC Media", "INFLUENCER CHAMBER", "FUNFINE MEDIA US", "NUOXIN", "CreatorBonus by ShoppeDance Inc.", "MliMli", "San Deng", "kosmarts", "CCA", "Lanxi", "Tourmaline", "DoumobMedia", "UGO Global Selling", "Vista", "Tif Creative", "KuiB", "WHALE.CULTURE", "Content Lab", "Joy Media", "Golden", "Ideas", "gate", "T-art Digital DE", "KEY TT", "Titans UGC", "Infinity Global Media", "FENDA", "PAP Mass Media", "Jdy management", "T Gen", "MCN Iberia", "Vortex Media", "Summers EasyMedia", "Commerce Social", "CARAVEL MEDIA", "JOVE UK", "TRUST NETWORK", "Famfluence Affiliate agency", "Dimension 6", "Tank Top Agency", "GEN Z GROUP", "Red Harp", "INLY MEDIA USA", "COMMERCIAL GROUP & IMPORTS DEMAZ", "OOIN MEDIA", "Trendii Talent DE", "Live and Vibrant", "THINKERAS", "Hongyue Technology", "MagicInfinite", "Style Sphere", "Flyfish", "Chong Xiao Wu", "Dream Bay Group", "DRI", "Adtoker Europe", "CreatorCore", "BSLM", "SAMRAAT Network", "Qiya Technology", "Aequora", "echooma", "We Marketing", "pp joy", "Wayward", "LKCX.Media", "Social Commerce Club", "Affiliate Automated", "Yowant US", "Aotuosi", "Western Boys", "TCA UK", "K-veri", "DTTLY", "907 Media LLC", "forest us", "weiyuan", "CHATTK", "Zhuo Hai", "Hieye", "Z&H", "Toyonet MX", "WONIU_Global", "AMMI", "Live Academy", "CREATIVA CLUB LLC", "HAR", "BOOST US", "yaochen", "YOWANT NETWORK", "Shoplooks", "HEMU", "JingHui E-commerce", "KKisland", "Bluetopia", "Flutter Labs LLC", "Mother Shoppin Partnership", "DELICIOUSFAST", "HENGxiangUS", "LOTTO", "Greenliv", "Koala & Tree", "Starry*", "Sparkling ES", "KEYWEB AGENCY", "GAXI", "YEAH FANS SOLUTIONS", "Force Awakens", "TourMateCN", "A-List Me", "Goya", "infiniite", "LightBulb Live", "TIKLATAM USA", "weiruistrong", "TELLING CLUB", "BIAOSHENG", "Whale Leap Star Path", "MuseAI", "drice", "Creator's Corner", "COMU US", "XIYOUFUN", "Solaris League", "YONO", "Affiniti Studios", "NoAging fr", "456 Growth", "STZC", "Ravyn", "Iris Rising", "GEEKO", "greenorange", "NUTS_", "MAXWELL STUDIOS", "FAITHFLUENCE", "Toothbuckle Agency", "Inprint Interactive", "Timeless Legacy", "FMKJ-UK", "Creatify", "PIGGYPAYUS", "Reach Digital", "Pence Creators", "Represent PR", "PEIPEINYC", "FTTV", "Bocen Media MX", "ANDVIDS", "SK_shuaiku", "NBCN LATAM, S. DE R.L. DE C.V.", "Miyaiscie Influencer", "sunnymedia", "Honey Drip Creators", "POWER OF BELIEVE", "Hamburger", "Binsen", "Vogue Rader", "Xingyi Plan", "CreatorBonus by ShoppeDance", "SANSU", "Memo Mexico", "Papaya Given", "saniversumm", "Pretty Center", "Lumen Edge", "YOUNGGUNS ENT SHOP", "Passion J", "Avocado DE", "FREEDOM WIND", "U.M.T US", "The Creator Loop", "BlueBag.CN", "Hangzhou Kangjun Health Management Consulting Co., Ltd", "SuperOrdinary USA", "Outlandish US", "BuyCoolBeans", "ZS", "Sun and Sky Entertainment", "Avocado US", "VibraVerse MX", "SDHH", "Clifton Media", "PROPE", "shiying-fashion", "Jiahang Media", "Iffert Media LLC", "Ninup", "LUNAHOLM US", "YZ", "GPL", "Holmburgh", "xlg start shop", "Shanmu Media", "VIKOC LLC", "TDV", "fleet", "Woke Network", "Xingxin Media", "Bonjour 4C", "Join Brands", "VICTORY INTERNATIONAL GROUP", "DorLene", "SinoClick US", "Ote MCN", "Bainiao", "CloudMorn", "Dream Building", "VHGROUP", "Befriends usa", "YUNSHI MCN", "1 Second", "Befriends MEDIA", "Rough Seas", "WUYEJI", "Luffy Media", "MAX INTERNATIONAL", "Star Creators", "Digital Third Rock Media, Inc.", "IceSpear", "Greatflowerus", "Ye Lab", "ENKIME", "Roots Marketing Agency", "Avocado", "Force Awakens MCN", "Unity Media", "Drakon", "Creator Depot Shop Agency", "Classic  Media", "MEDIGLPE", "NewStar_US", "Efluencer", "Bigs cat", "Blue Whale Media", "JAXE", "GreenWood MCN", "SHUPINTECHNOLOGY", "VansinoNetwork", "Boundless MGMT", "maze us", "UnityWave", "Evolution", "Joanna&Eleven", "MIYUKI", "RIGHT WORK", "Marketinglama", "JW-TAP", "Pattern US", "OUMEIHUI media", "Foreversea US", "Yean", "Qian fan  Cross-border", "Nat Pack Nation", "BJ QMZX", "Evergreen", "BIG SKY TOWING", "Lucky Focus", "New Beginnings Agency", "QIWEIMEDIA", "BoBoMedia", "OANNY FASHION", "InfluenceBridge", "NULL", "Total总计", "CJ Media", "MaGo-Force", "Meiyang MX", "Windboss", "itsumo.inc (Peace Creation)", "LIVE COMMERCE JAPAN (LCJ)", "Fisherrni", "GZTIANFU", "Live Spark", "XiaoXi Culture", "JiangXi Mars", "starfuse"];

// ===== 站点配置 =====
const SITE_CONFIG = {
  siteName: "女装选品小站",
  // 数据文件路径（相对于 index.html）
  dataFile: "data/products.csv",
  // 访问口令（SHA-256 哈希）：拥有口令即可进入，机构信息维护在本地浏览器
  // 原文不落地，源码/网页里只出现哈希；如需改口令，用 SHA-256 重算此值即可
  accessCodeHash: "7f26783b113742110dfd737aaaf30eba0b2af75585ba07f821c8091d61455b22",
  // 管理员口令（SHA-256 哈希）：用于进入后台更新货盘（私密，不在页面明示）
  adminCodeHash: "15986b5e63da2ae25a69190ff752f9e970830325be5216374c7d1a48004c6228",
  // 登录页提示
  loginTitle: "女装选品小站",
  loginSubtitle: "请输入访问口令进入",
  // 货盘分类（name + enabled）
  pallets: [
    { name: "总商品底池", key: "all", color: "green", enabled: true },
    { name: "直播货盘", key: "live", color: "orange", enabled: false },
    { name: "短视频货盘", key: "video", color: "blue", enabled: false },
    { name: "官方货盘", key: "official", color: "purple", enabled: false },
    { name: "AI 货盘", key: "ai", color: "pink", enabled: false },
  ],
};
